### ISSUE TITLE
Extending the functionality to support building the catalog on tape holdings and campaign storage

### ISSUE THREAD

**Issue by andersy005** [NCAR/intake-esm#10]
References:
- http://pal.mgleicher.us/HSI/hsi/hsi_reference_manual_2/hsi_commands_-_alphabetical.html
- https://github.com/NCAR/cmip6_cesm/blob/master/get_cesm1.py

**Comment by matt-long** [comment]
A few additional notes. 

1. This inherently involves specificity to the NCAR machines.

1. For a particular collection, like the CESM-LE, you can generate a complete listing of files on tape using something like
```hsi "find /CCSM/csm/CESM-CAM5-BGC-LE -name "*.nc"" &> cesm-le-files```
For the CESM-LE, it should be the case that the tape archive is complete, i.e. only a subset are on disk.

1. Tape is on the way out, as I understand it, but another resource we have at NCAR is the campaign storage, which is accessed via Globus. Globus command line tools may provide access/listing capabilities.

**Comment by andersy005** [comment]
@matt-long, 

> Tape is on the way out, as I understand it, but another resource we have at NCAR is the campaign storage, which is accessed via Globus. Globus command line tools may provide access/listing capabilities.

Globus-cli sounds like a great tool for this. It would be great to support this feature

**Comment by andersy005** [comment]
@matt-long 

- Apart from tape holdings and campaign storage, are there any other foreseeable related functionality that we need to have on our roadmap?

- Are you happy with current support of tape holdings? Any missing important features?

- How much priority would you give to campaign storage support?

**Comment by matt-long** [comment]
@andersy005, I think we should have "Globus" support, which encompasses campaign storage, but is much more general. I think this is a high priority. 

We should have a means of curating named Globus "endpoints." 

We currently assess holdings on tape (and could easily extend this to Globus), but do not have an automated means of accessing them. This is missing functionality.  

Requirements:
- We need to be able to recognize data resources (files) that are identical, but perhaps in different locations;
- Have a prioritization of access locations, based on `direct_access` attribute. 
- If the only location has `direct_access = False`, the system should be able to automatically transfer and cache the file. 

I am still worried about our defaults for the cache directory in $HOME. This will be problematic—it's almost better to not have a default and force the user to specify.

**Comment by andersy005** [comment]
> I am still worried about our defaults for the cache directory in $HOME. This will be problematic

One solution is to use `data_cache_directory: $TMPDIR/intake_esm/data_cache`

```bash
$ echo $TMPDIR
/glade/scratch/abanihi
```

And since our config.py can expand environment variables, I expect this to work. In case this is not a good solution, then we could force the user to specify this location.

**Comment by matt-long** [comment]
That's definitely better than home. I am not sure $TMPDIR is reliably set on all systems, but we could try and throw an exception if not.

I think we need to thing thru the configuration details a bit....maybe a new issues. When the package is updated, the user configuration yaml files are not updated. As the definition/requirements of these files change with development, package updates lead to inconsistencies. 

Is there a way to ensure more robust package updates in this context?

**Comment by andersy005** [comment]
> I think we need to thing thru the configuration details a bit....maybe a new issue. When the package is updated, the user configuration yaml files are not updated. As the definition/requirements of these files change with development, package updates lead to inconsistencies.

You mentioned this in #47. I agree with you

> Is there a way to ensure more robust package updates in this context?

I was thinking that we could overwrite the configuration at import time by comparing the content of  `~/.intake_esm/config.yaml` and the content of `config.yaml` in the package (I don't think this is a good idea though since it is not clear to me which content takes precedence over which).


The solution you proposed in #47 sounds like a step in the right direction 

> One thing that might help would be to separate config.yaml into two files: config-collections.yaml and config-user.yaml. At this point, the latter would contain
> 
> default_chunk_size: 128MiB
> data_cache_directory: ~/.intake_esm/data_cache
> database_directory: ~/.intake_esm/collections

**Comment by andersy005** [comment]
> I am not sure $TMPDIR is reliably set on all systems, but we could try and throw an exception if not.

A try and except block will solve our problems

**Comment by andersy005** [comment]
Closing this as #135 removed catalog building functionality from intake-esm.
