### ISSUE TITLE
Problems with `to_xarray` on CESM-LE

### ISSUE THREAD

**Issue by matt-long** [NCAR/intake-esm#100]
I am finding that loading data from the atmosphere component in the CESM-LE is problematic. 

I have uncovered 2 errors:
1. there is an inconsistency in the time axis for ensemble member 1 resulting from the fact that 2 files cover part of the same time period:
>b.e11.B20TRC5CNBDRD.f09_g16.001.cam.h0.TS.185001-200512.nc
b.e11.B20TRC5CNBDRD.f09_g16.001.cam.h0.TS.192001-200512.nc

1. some of the ensemble members include additional variables in the time series files (related to COSP simulation). This causes the ensemble merge in `aggregate.py` to fail.

Here's gist demonstrating the errors:
https://gist.github.com/matt-long/bf4ee82ad797906599fd054c5f56e63e

To address 2, we should test for common vars across the datasets and drop the additional variables before concatenating.

Addressing 1 may be more complicated. We would likely have to detect overlapping time-windows when building the catalog. If this turns out to be a common problem, we should think about how to address. If it's not a common problem, perhaps we should just add the problematic file (b.e11.B20TRC5CNBDRD.f09_g16.001.cam.h0.TS.192001-200512.nc) to the `exclude_dirs` list.

**Comment by matt-long** [comment]
Updated intake-esm-datastore to deal with the duplicate data issue.
https://github.com/NCAR/intake-esm-datastore/pull/10

**Comment by andersy005** [comment]
@matt-long, thank you for documenting this issue and addressing the first part of the issue. I encountered the second part of the issue while working on the zarrification of `cam` component of CESM-LENS data. At the time, I didn't have time to look into ways to fix it.

**Comment by matt-long** [comment]
I think this is addressed by #102.
