### ISSUE TITLE
Mismatch in numerical precision on the latitudes of the CESM ensemble members (34, 35 and 101-105) for atmospheric variables 

### ISSUE THREAD

**Issue by andersy005** [NCAR/intake-esm#104]
It appears that the numerical precision on the latitudes of the last 7 ensemble members (numbers 34, 35 and 101-105) for atmospheric variables is actually different than on the first 33 members.  

This causes problems when trying to use xarray to concatenate the members together into a single dataset, as xarray would try to merge both of the latitude arrays and effectively double the size of the latitude dimension. 

```python
In [12]: z = xr.open_dataset("/glade/collections/cdg/data/cesmLE/CESM-CAM5-BGC-LE/atm/proc/tseries/monthly/TS/b.e11.B20TRC5CNBDRD.f09_g16.003.cam.h
    ...: 0.TS.192001-200512.nc").lat
    ...:

In [13]: x = xr.open_dataset("/glade/collections/cdg/data/cesmLE/CESM-CAM5-BGC-LE/atm/proc/tseries/monthly/TS/b.e11.B20TRC5CNBDRD.f09_g16.105.cam.h
    ...: 0.TS.192001-200512.nc").lat

In [14]: y = xr.open_dataset("/glade/collections/cdg/data/cesmLE/CESM-CAM5-BGC-LE/atm/proc/tseries/monthly/TS/b.e11.B20TRC5CNBDRD.f09_g16.104.cam.h
    ...: 0.TS.192001-200512.nc").lat

In [15]: xr.testing.assert_identical(x, y)

In [16]: xr.testing.assert_identical(z, y)
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-16-a0aa58e132f5> in <module>
----> 1 xr.testing.assert_identical(z, y)

/glade/work/abanihi/softwares/miniconda3/envs/analysis/lib/python3.7/site-packages/xarray/testing.py in assert_identical(a, b)
     88     elif isinstance(a, DataArray):
     89         assert a.name == b.name
---> 90         assert a.identical(b), formatting.diff_array_repr(a, b, 'identical')
     91     elif isinstance(a, (Dataset, Variable)):
     92         assert a.identical(b), formatting.diff_dataset_repr(a, b, 'identical')

AssertionError: Left and right DataArray objects are not identical

Differing values:
L
    array([-90.      , -89.057592, -88.115183, -87.172775, -86.230366, -85.287958,
           -84.34555 , -83.403141, -82.460733, -81.518325, -80.575916, -79.633508,
           -78.691099, -77.748691, -76.806283, -75.863874, -74.921466, -73.979058,
           -73.036649, -72.094241, -71.151832, -70.209424, -69.267016, -68.324607,
           -67.382199, -66.439791, -65.497382, -64.554974, -63.612565, -62.670157,
           -61.727749, -60.78534 , -59.842932, -58.900524, -57.958115, -57.015707,
           -56.073298, -55.13089 , -54.188482, -53.246073, -52.303665, -51.361257,
           -50.418848, -49.47644 , -48.534031, -47.591623, -46.649215, -45.706806,
           -44.764398, -43.82199 , -42.879581, -41.937173, -40.994764, -40.052356,
           -39.109948, -38.167539, -37.225131, -36.282723, -35.340314, -34.397906,
           -33.455497, -32.513089, -31.570681, -30.628272, -29.685864, -28.743455,
           -27.801047, -26.858639, -25.91623 , -24.973822, -24.031414, -23.089005,
           -22.146597, -21.204188, -20.26178 , -19.319372, -18.376963, -17.434555,
           -16.492147, -15.549738, -14.60733 , -13.664921, -12.722513, -11.780105,
           -10.837696,  -9.895288,  -8.95288 ,  -8.010471,  -7.068063,  -6.125654,
            -5.183246,  -4.240838,  -3.298429,  -2.356021,  -1.413613,  -0.471204,
             0.471204,   1.413613,   2.356021,   3.298429,   4.240838,   5.183246,
             6.125654,   7.068063,   8.010471,   8.95288 ,   9.895288,  10.837696,
            11.780105,  12.722513,  13.664921,  14.60733 ,  15.549738,  16.492147,
            17.434555,  18.376963,  19.319372,  20.26178 ,  21.204188,  22.146597,
            23.089005,  24.031414,  24.973822,  25.91623 ,  26.858639,  27.801047,
            28.743455,  29.685864,  30.628272,  31.570681,  32.513089,  33.455497,
            34.397906,  35.340314,  36.282723,  37.225131,  38.167539,  39.109948,
            40.052356,  40.994764,  41.937173,  42.879581,  43.82199 ,  44.764398,
            45.706806,  46.649215,  47.591623,  48.534031,  49.47644 ,  50.418848,
            51.361257,  52.303665,  53.246073,  54.188482,  55.13089 ,  56.073298,
            57.015707,  57.958115,  58.900524,  59.842932,  60.78534 ,  61.727749,
            62.670157,  63.612565,  64.554974,  65.497382,  66.439791,  67.382199,
            68.324607,  69.267016,  70.209424,  71.151832,  72.094241,  73.036649,
            73.979058,  74.921466,  75.863874,  76.806283,  77.748691,  78.691099,
            79.633508,  80.575916,  81.518325,  82.460733,  83.403141,  84.34555 ,
            85.287958,  86.230366,  87.172775,  88.115183,  89.057592,  90.      ])
R
    array([-90.      , -89.057592, -88.115183, -87.172775, -86.230366, -85.287958,
           -84.34555 , -83.403141, -82.460733, -81.518325, -80.575916, -79.633508,
           -78.691099, -77.748691, -76.806283, -75.863874, -74.921466, -73.979058,
           -73.036649, -72.094241, -71.151832, -70.209424, -69.267016, -68.324607,
           -67.382199, -66.439791, -65.497382, -64.554974, -63.612565, -62.670157,
           -61.727749, -60.78534 , -59.842932, -58.900524, -57.958115, -57.015707,
           -56.073298, -55.13089 , -54.188482, -53.246073, -52.303665, -51.361257,
           -50.418848, -49.47644 , -48.534031, -47.591623, -46.649215, -45.706806,
           -44.764398, -43.82199 , -42.879581, -41.937173, -40.994764, -40.052356,
           -39.109948, -38.167539, -37.225131, -36.282723, -35.340314, -34.397906,
           -33.455497, -32.513089, -31.570681, -30.628272, -29.685864, -28.743455,
           -27.801047, -26.858639, -25.91623 , -24.973822, -24.031414, -23.089005,
           -22.146597, -21.204188, -20.26178 , -19.319372, -18.376963, -17.434555,
           -16.492147, -15.549738, -14.60733 , -13.664921, -12.722513, -11.780105,
           -10.837696,  -9.895288,  -8.95288 ,  -8.010471,  -7.068063,  -6.125654,
            -5.183246,  -4.240838,  -3.298429,  -2.356021,  -1.413613,  -0.471204,
             0.471204,   1.413613,   2.356021,   3.298429,   4.240838,   5.183246,
             6.125654,   7.068063,   8.010471,   8.95288 ,   9.895288,  10.837696,
            11.780105,  12.722513,  13.664921,  14.60733 ,  15.549738,  16.492147,
            17.434555,  18.376963,  19.319372,  20.26178 ,  21.204188,  22.146597,
            23.089005,  24.031414,  24.973822,  25.91623 ,  26.858639,  27.801047,
            28.743455,  29.685864,  30.628272,  31.570681,  32.513089,  33.455497,
            34.397906,  35.340314,  36.282723,  37.225131,  38.167539,  39.109948,
            40.052356,  40.994764,  41.937173,  42.879581,  43.82199 ,  44.764398,
            45.706806,  46.649215,  47.591623,  48.534031,  49.47644 ,  50.418848,
            51.361257,  52.303665,  53.246073,  54.188482,  55.13089 ,  56.073298,
            57.015707,  57.958115,  58.900524,  59.842932,  60.78534 ,  61.727749,
            62.670157,  63.612565,  64.554974,  65.497382,  66.439791,  67.382199,
            68.324607,  69.267016,  70.209424,  71.151832,  72.094241,  73.036649,
            73.979058,  74.921466,  75.863874,  76.806283,  77.748691,  78.691099,
            79.633508,  80.575916,  81.518325,  82.460733,  83.403141,  84.34555 ,
            85.287958,  86.230366,  87.172775,  88.115183,  89.057592,  90.      ])
Differing coordinates:
L * lat      (lat) float64 -90.0 -89.06 -88.12 -87.17 ... 87.17 88.12 89.06 90.0
    long_name: latitude
    units: degrees_north
R * lat      (lat) float64 -90.0 -89.06 -88.12 -87.17 ... 87.17 88.12 89.06 90.0
    long_name: latitude
    units: degrees_north

```

![Screen Shot 2019-07-17 at 1 32 44 PM](https://user-images.githubusercontent.com/13301940/61405585-6801fe80-a897-11e9-825f-2bcb3cdde8b2.png)
![Screen Shot 2019-07-17 at 1 32 33 PM](https://user-images.githubusercontent.com/13301940/61405590-6b958580-a897-11e9-9688-99c18914a24d.png)

One possible solution is to  overwrite the latitude coordinate array on all files to be the same thing (drawn from the first member) before doing the xarray concatenation at runtime.

Cc @matt-long, @kmpaul, @jukent

**Comment by andersy005** [comment]
> One possible solution is to overwrite the latitude coordinate array on all files to be the same thing (drawn from the first member) before doing the xarray concatenation at runtime.


The more I think about this, the more I question whether this is a robust/long-term solution...

**Comment by kmpaul** [comment]
If you can do a diff on the latitude values between the "good" and "bad" datasets, and the diff is "small", then overwriting the latitude coordinate array on all of the "bad" datasets should be fine.

You could add a check for "small diffs" in the xarray concat method to see if they can be treated as identical.

**Comment by matt-long** [comment]
This is partially a result of lossy compression applied to a subset of the data.

>One possible solution is to overwrite the latitude coordinate array on all files to be the same thing (drawn from the first member) before doing the xarray concatenation at runtime.

We are already taking the coordinates from the first dataset:
https://github.com/NCAR/intake-esm/blob/e83f1530fd412ba066fa45979098eea8b886a7b1/intake_esm/aggregate.py#L171

The problem happens in the explicit `xr.align` step. I think the right approach is to modify `xarray.align` to include a `tolerance` argument. This has been discussed:
https://github.com/NCAR/intake-esm/blob/e83f1530fd412ba066fa45979098eea8b886a7b1/intake_esm/aggregate.py#L167
https://github.com/pydata/xarray/issues/2217

**Comment by andersy005** [comment]
I am running into a "similar" issue with the daily land data for RCP85 experiment: https://nbviewer.jupyter.org/gist/andersy005/292c68bd65ab492f31eca73cc9a3d67a/zarrification-land-daily.ipynb

If anyone understands what's really going on here, I would appreciate your help in figuring out how to fix this one too.

**Comment by matt-long** [comment]
@andersy005, I think what's going on is that round-off level differences in coordinates are being treated as truly different coordinate values. This is almost certainly happening in our `xr.align` step. 

The only coordinate we really want to `align` is `time`. 

We could rearrange our steps and do something like 
1. get all dim sizes for all dim coordinates except `time`
1. check that all dim sizes match
1. drop all dim coordinate variables from dsets[1:]
1. apply `xr.align`

**Comment by andersy005** [comment]
@matt-long, thank you for chiming in! I am going to explore your proposed steps and will let you know how it goes...

**Comment by andersy005** [comment]
@matt-long, 

> This is almost certainly happening in our xr.align step.

I just ran a small experiment, and found out that the issue is happening in other places other than `xr.align`, namely in the concat step in `concat_time_levels()`:

https://github.com/NCAR/intake-esm/blob/e83f1530fd412ba066fa45979098eea8b886a7b1/intake_esm/aggregate.py#L133-L135

See the notebook for a minimal example: 

https://nbviewer.jupyter.org/gist/andersy005/292c68bd65ab492f31eca73cc9a3d67a/coords_mismatch.ipynb

**Comment by matt-long** [comment]
I think if you applied the `xr.align` first (as is done in aggregate.py), it would happen there. `xr.concat` is applying `xr.align` behind the scenes. The problem is that we're only dropping `non_dim_coords`; we need to also drop `dim_coords_except_time` before applying the `xr.align`.

**Comment by dcherian** [comment]
You can pass `join='exact'` to `xr.align` to make xarray raise an error when this happens instead of doing the default outer `join`. Then at least it doesn't happen silently.

Or if you're ambitious you can implement `join='override'` in xarray (https://github.com/pydata/xarray/issues/2217) :)

**Comment by matt-long** [comment]
Thanks @dcherian. Unfortunately, we want different `join` behavior for different coordinates. We do want `join=inner` (or `join=outer`) for `time`, but not for the other coordinate (i.e., x, y, z).  We implemented the `override` work around yesterday, applied to all coords but `time`.

**Comment by dcherian** [comment]
Sounds like you have a solution but FWIW `xr.align(*ds, join='exact', exclude='time')` and then `xr.concat(dim='time')` is what you want (I think). 

I have an open PR to add `join` as a `concat` kwarg which will make this even easier.

**Comment by matt-long** [comment]
Yes, except we need `xr.align(*ds, join='override', exclude='time')` or `xr.align(*ds, tolerance=xtol, exclude='time')`.

**Comment by matt-long** [comment]
Actually, my last comment there is not accurate.  

What we want require is different join options for different coordinates. 
```python
dsets_aligned_time  = xr.align(*dsets, join=kwargs['join'], exclude=all_but_time)
dsets_aligned  = xr.align(*dsets_aligned_time, tolerance=xtol, exclude='time')
 ```
