### ISSUE TITLE
Pass urlpath through call stack for optional use in Collection._get_file_attrs(f,urlpath)

### ISSUE THREAD

**Issue by pbranson** [NCAR/intake-esm#106]
When prototyping a Collection and Source object for use with an internal collection of netcdfs, I came across some possible feature enhancements:

1. Our collection has several sets at differing root locations across different computing resources - giving access to urlpath when parsing the filename template with `_get_file_attrs` helps make the collection code more generic.
2. order-by-columns does not apply after initial collection creation, only after `get_subset`, add attribute to collection upon creation and sort initial dataframe.

Combining urlpath with the neat `intake.source.utils.reverse_format` makes for some clean example parsing code:

```
    def _get_file_attrs(self, filepath, urlpath):

         path_fmt = urlpath + '{model_version}/{grid}/{level}/y{year:d}/m{month:d}/{forecast_date:%Y%m%d}/{rg:1s}{forecast_hour:d}.nc'
        try:
            fileparts = reverse_format(path_fmt, filepath)
        except ValueError:
            raise ValueError('Failed to parse ' + filepath)

        fileparts['file_basename'] = os.path.basename(filepath)
        fileparts['file_dirname'] = os.path.dirname(filepath) + '/'
        fileparts['file_fullpath'] = filepath
        fileparts['product_type'] = 'forecast'

         return fileparts
```

I can submit a PR for 1. and 2. if that would be useful.

**Comment by andersy005** [comment]
Thank you, @pbranson! I wasn't aware of the `intake.source.utils.reverse_format` feature. It is really neat... 

> I can submit a PR for 1. and 2. if that would be useful.

That will be great
