### ISSUE TITLE
Parse collection yaml files with jinja templating provided by intake

### ISSUE THREAD

**Issue by pbranson** [NCAR/intake-esm#116]
At present it is not possible to use jinja templating in the collection yaml files. It would be good if this was handled consistently with the way that intake does this - however I havent investigated what is required to do that.

For example, I attempted to include an environment variable that altered the base path to the collection depending on the host I was working on.

**Comment by andersy005** [comment]
@pbranson, with #135, we rewrote intake-esm in a way that doesn't require the input YAML files  (i.e. the `collection building` step does not exist in intake-esm anymore). We introduced the esm-collection-spec: https://github.com/NCAR/esm-collection-spec, as a way of making `intake-esm` general enough.
