### ISSUE TITLE
KeyError when building or col.to_xarray() after update

### ISSUE THREAD

**Issue by aaronspring** [NCAR/intake-esm#123]
### Description

I updated from some version from april 19 to the most recent versions because when loading CMIP6 data I got sometimes errors when `cat.to_dask()` because a single of the models selected threw some error. Based on browsing some isses like https://github.com/NCAR/intake-esm/issues/76 I thought updating would be a good idea. It used to work before. I built collections for cmip5 and cmip6 and got them into xarray.

However, now things don't work anymore. I also wanted to get the most recent versions and therefore updated via `pip install git+https...` because intake-xarray is only on conda-forge in version 0.3.0.

I now get `KeyError`s asking for `location` or `direct_access`. However my collection_input_definition file doesnt have `location` and the `pd.df` doesnt have `direct_access`. 
Based on the documentation I didnt find changes in this part.

### What I Did

```
collection_input_definition = '/home/mpim/m300524/pymistral/intake/cmip5_collection_mistral.yml'
# problem existis also for cmip6 collection
!cat /home/mpim/m300524/pymistral/intake/cmip5_collection_mistral.yml | head -10
name: cmip5_collection_mistral
collection_type: cmip5
data_sources:
  root_dir:
    name: MISTRAL
    loc_type: posix
    direct_access: True
    urlpath: /work/kd0956/CMIP5/data/cmip5

col = intake.open_esm_metadatastore(collection_input_definition=collection_input_definition, overwrite_existing=True)
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-5-554feb33ee30> in <module>
----> 1 col = intake.open_esm_metadatastore(collection_input_definition=collection_input_definition, overwrite_existing=True)

/work/mh0727/m300524/anaconda3/envs/pymistral/lib/python3.7/site-packages/intake_esm/core.py in __init__(self, collection_input_definition, collection_name, overwrite_existing, storage_options, **kwargs)
     88                 collection_input_definition, **kwargs
     89             )
---> 90             self._build_collection(overwrite_existing)
     91 
     92         else:

/work/mh0727/m300524/anaconda3/envs/pymistral/lib/python3.7/site-packages/intake_esm/core.py in _build_collection(self, overwrite_existing)
    138         if name not in self.collections or overwrite_existing:
    139             cc = ESMMetadataStoreCatalog.collection_types[self.collection_type]
--> 140             cc = cc(self.input_collection, fs=self.fs)
    141             cc.build()
    142             self._get_built_collections()

/work/mh0727/m300524/anaconda3/envs/pymistral/lib/python3.7/site-packages/intake_esm/collection.py in __init__(self, collection_spec, fs)
     54             )
     55         self.df = pd.DataFrame(columns=self.columns)
---> 56         self.exclude_patterns = self._get_exclude_patterns()
     57         self.database_base_dir = config.get('database-directory', None)
     58         self.order_by_columns = self.collection_definition.get('order-by-columns')

/work/mh0727/m300524/anaconda3/envs/pymistral/lib/python3.7/site-packages/intake_esm/collection.py in _get_exclude_patterns(self)
    244         data_sources = collection_spec['data_sources']
    245         for data_source, data_source_attrs in data_sources.items():
--> 246             locations = data_source_attrs['locations']
    247             for loc in locations:
    248                 exclude = loc.get('exclude_patterns', None) or loc.get('exclude_dirs', None)

KeyError: 'locations'
```

```
col = intake.open_esm_metadatastore(collection_input_definition=collection_input_definition, overwrite_existing=False)
cat = col.search(experiment='historical',variable=v,mip_table='Amon',ensemble_member=ensemble_member)
hist = cat.to_dask()
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
/work/mh0727/m300524/anaconda3/envs/pymistral/lib/python3.7/site-packages/pandas/core/indexes/base.py in get_loc(self, key, method, tolerance)
   2655             try:
-> 2656                 return self._engine.get_loc(key)
   2657             except KeyError:

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

KeyError: 'direct_access'

During handling of the above exception, another exception occurred:

KeyError                                  Traceback (most recent call last)
<ipython-input-13-bea7f880dbf3> in <module>
----> 1 hist = cat.to_dask()

/work/mh0727/m300524/anaconda3/envs/pymistral/lib/python3.7/site-packages/intake_xarray/base.py in to_dask(self)
     67     def to_dask(self):
     68         """Return xarray object where variables are dask arrays"""
---> 69         return self.read_chunked()
     70 
     71     def close(self):

/work/mh0727/m300524/anaconda3/envs/pymistral/lib/python3.7/site-packages/intake_xarray/base.py in read_chunked(self)
     42     def read_chunked(self):
     43         """Return xarray object (which will have chunks)"""
---> 44         self._load_metadata()
     45         return self._ds
     46 

/work/mh0727/m300524/anaconda3/envs/pymistral/lib/python3.7/site-packages/intake/source/base.py in _load_metadata(self)
    115         """load metadata only if needed"""
    116         if self._schema is None:
--> 117             self._schema = self._get_schema()
    118             self.datashape = self._schema.datashape
    119             self.dtype = self._schema.dtype

/work/mh0727/m300524/anaconda3/envs/pymistral/lib/python3.7/site-packages/intake_esm/source.py in _get_schema(self)
    141 
    142         if self._ds is None:
--> 143             self._open_dataset()
    144 
    145             if isinstance(self._ds, xr.Dataset):

/work/mh0727/m300524/anaconda3/envs/pymistral/lib/python3.7/site-packages/intake_esm/cmip.py in _open_dataset(self)
     72             member_column_name='ensemble_member',
     73             variable_column_name='variable',
---> 74             file_fullpath_column_name='file_fullpath',
     75         )
     76 

/work/mh0727/m300524/anaconda3/envs/pymistral/lib/python3.7/site-packages/intake_esm/source.py in _open_dataset_groups(self, dataset_fields, member_column_name, variable_column_name, file_fullpath_column_name, file_basename_column_name)
     85         query_results = get_subset(self.collection_name, self.query)
     86         query_results = _ensure_file_access(
---> 87             query_results, file_fullpath_column_name, file_basename_column_name
     88         )
     89         grouped = query_results.groupby(dataset_fields)

/work/mh0727/m300524/anaconda3/envs/pymistral/lib/python3.7/site-packages/intake_esm/storage.py in _ensure_file_access(query_results, file_fullpath_column_name, file_basename_column_name)
    273     file_remote_local = {k: [] for k in resource_types.keys()}
    274 
--> 275     query_results = _filter_query_results(query_results, file_basename_column_name)
    276 
    277     local_urlpaths = []

/work/mh0727/m300524/anaconda3/envs/pymistral/lib/python3.7/site-packages/intake_esm/storage.py in _filter_query_results(query_results, file_basename_column_name)
    235     for _, group in groups:
    236 
--> 237         g = group[group['direct_access']]
    238         # File does not exist on resource with high priority
    239         if g.empty:

/work/mh0727/m300524/anaconda3/envs/pymistral/lib/python3.7/site-packages/pandas/core/frame.py in __getitem__(self, key)
   2925             if self.columns.nlevels > 1:
   2926                 return self._getitem_multilevel(key)
-> 2927             indexer = self.columns.get_loc(key)
   2928             if is_integer(indexer):
   2929                 indexer = [indexer]

/work/mh0727/m300524/anaconda3/envs/pymistral/lib/python3.7/site-packages/pandas/core/indexes/base.py in get_loc(self, key, method, tolerance)
   2656                 return self._engine.get_loc(key)
   2657             except KeyError:
-> 2658                 return self._engine.get_loc(self._maybe_cast_indexer(key))
   2659         indexer = self.get_indexer([key], method=method, tolerance=tolerance)
   2660         if indexer.ndim > 1 or indexer.size > 1:

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

KeyError: 'direct_access'
```
### Output of ``intake_esm.__version__``

<details>

'2019.8.5.post20'

</details>

### Output of ``conda list``
I installed intake, intake-esm, intake-xarray via pip because intake-xarray 0.3.1 wasnt on conda-forge.
<details>

# packages in environment at /work/mh0727/m300524/anaconda3/envs/pymistral:
#
# Name                    Version                   Build  Channel
appdirs                   1.4.3                      py_1    conda-forge
asciitree                 0.3.3                      py_2    conda-forge
asn1crypto                0.24.0                py37_1003    conda-forge
attrs                     18.2.0                     py_0    conda-forge
backcall                  0.1.0                      py_0    conda-forge
blas                      1.1                    openblas    conda-forge
bleach                    3.1.0                      py_0    conda-forge
bokeh                     1.0.4                 py37_1000    conda-forge
boto3                     1.9.206                  pypi_0    pypi
botocore                  1.12.206                 pypi_0    pypi
bzip2                     1.0.6             h14c3975_1002    conda-forge
ca-certificates           2019.6.16            hecc5488_0    conda-forge
cartopy                   0.17.0          py37h0aa2c8f_1004    conda-forge
cdo                       1.9.5             he2b4288_1005    conda-forge
certifi                   2019.6.16                py37_1    conda-forge
cffi                      1.11.5          py37h9745a5d_1001    conda-forge
cftime                    1.0.3.4         py37hd352d35_1001    conda-forge
chardet                   3.0.4                 py37_1003    conda-forge
click                     7.0                        py_0    conda-forge
cloudpickle               0.7.0                      py_0    conda-forge
cryptography              2.5              py37h1ba5d50_0
curl                      7.62.0               hbc83047_0
cycler                    0.10.0                     py_1    conda-forge
cytoolz                   0.9.0.1         py37h14c3975_1001    conda-forge
dask                      2.2.0                    pypi_0    pypi
dask-jobqueue             0.4.1                      py_0    conda-forge
dbus                      1.13.2               h714fa37_1
decorator                 4.3.2                      py_0    conda-forge
distributed               1.25.3                   py37_0    conda-forge
docrep                    0.2.5                      py_0    conda-forge
docutils                  0.14                     pypi_0    pypi
eccodes                   2.11.0            hb25bff7_1007    conda-forge
entrypoints               0.3                   py37_1000    conda-forge
expat                     2.2.5             hf484d3e_1002    conda-forge
fasteners                 0.14.1                     py_3    conda-forge
fftw                      3.3.8             h14c3975_1002    conda-forge
fontconfig                2.13.1            h2176d3f_1000    conda-forge
freetype                  2.9.1             h94bbf69_1005    conda-forge
fsspec                    0.4.1                    pypi_0    pypi
geos                      3.7.1             hf484d3e_1000    conda-forge
gettext                   0.19.8.1          h9745a5d_1001    conda-forge
glib                      2.56.2            had28632_1001    conda-forge
gst-plugins-base          1.14.0               hbbd80ab_1
gstreamer                 1.14.0               hb453b48_1
hdf4                      4.2.13            h9a582f1_1002    conda-forge
hdf5                      1.10.4          nompi_h11e915b_1105    conda-forge
heapdict                  1.0.0                 py37_1000    conda-forge
icu                       58.2              hf484d3e_1000    conda-forge
idna                      2.8                   py37_1000    conda-forge
intake                    0.5.3                    pypi_0    pypi
intake-esm                2019.8.5.post20          pypi_0    pypi
intake-xarray             0.3.1+8.gcbea75c          pypi_0    pypi
ipykernel                 5.1.0           py37h24bf2e0_1002    conda-forge
ipython                   7.2.0           py37h24bf2e0_1000    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
jasper                    1.900.1           h07fcdf6_1006    conda-forge
jedi                      0.13.2                py37_1000    conda-forge
jinja2                    2.10                       py_1    conda-forge
jmespath                  0.9.4                    pypi_0    pypi
jpeg                      9c                h14c3975_1001    conda-forge
jsonschema                3.0.0a3               py37_1000    conda-forge
jupyter_client            5.2.4                      py_1    conda-forge
jupyter_core              4.4.0                      py_0    conda-forge
jupyterlab                0.35.4                   py37_0    conda-forge
jupyterlab_server         0.2.0                      py_0    conda-forge
kiwisolver                1.0.1           py37h6bb024c_1002    conda-forge
libaec                    1.0.3                hf484d3e_0    conda-forge
libcurl                   7.62.0               h20c2e04_0
libffi                    3.2.1             hf484d3e_1005    conda-forge
libgcc-ng                 7.3.0                hdf63c60_0    conda-forge
libgfortran-ng            7.2.0                hdf63c60_3    conda-forge
libiconv                  1.15              h14c3975_1004    conda-forge
libnetcdf                 4.6.2             hbdf4f91_1001    conda-forge
libpng                    1.6.36            h84994c4_1000    conda-forge
libsodium                 1.0.16            h14c3975_1001    conda-forge
libssh2                   1.8.0                         1    conda-forge
libstdcxx-ng              7.3.0                hdf63c60_0    conda-forge
libtiff                   4.0.10            h648cc4a_1001    conda-forge
libuuid                   2.32.1            h14c3975_1000    conda-forge
libxcb                    1.13              h14c3975_1002    conda-forge
libxml2                   2.9.8             h143f9aa_1005    conda-forge
libxslt                   1.1.32            h4785a14_1002    conda-forge
locket                    0.2.0                      py_2    conda-forge
lxml                      4.3.1            py37h23eabaa_0    conda-forge
markupsafe                1.1.0           py37h14c3975_1000    conda-forge
matplotlib                3.0.2                 py37_1002    conda-forge
matplotlib-base           3.0.2           py37h167e16e_1002    conda-forge
mistune                   0.8.4           py37h14c3975_1000    conda-forge
monotonic                 1.5                        py_0    conda-forge
msgpack-numpy             0.4.4.3                    py_0    conda-forge
msgpack-python            0.6.1            py37h6bb024c_0    conda-forge
nbconvert                 5.3.1                      py_1    conda-forge
nbformat                  4.4.0                      py_1    conda-forge
ncurses                   6.1               hf484d3e_1002    conda-forge
netcdf4                   1.5.1.2          py37had58050_0    conda-forge
notebook                  5.7.4                 py37_1000    conda-forge
numcodecs                 0.6.3            py37hf484d3e_0    conda-forge
numpy                     1.16.1          py37_blas_openblash1522bff_0  [blas_openblas]  conda-forge
olefile                   0.46                       py_0    conda-forge
openblas                  0.3.3             h9ac9557_1001    conda-forge
openssl                   1.1.1c               h516909a_0    conda-forge
ossuuid                   1.6.2             hf484d3e_1000    conda-forge
owslib                    0.17.1                     py_0    conda-forge
packaging                 19.0                       py_0    conda-forge
pandas                    0.24.1           py37hf484d3e_0    conda-forge
pandoc                    2.6                           1    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
parso                     0.3.3                      py_0    conda-forge
partd                     0.3.9                      py_0    conda-forge
patsy                     0.5.1                      py_0    conda-forge
pcre                      8.42                 h439df22_0
pexpect                   4.6.0                 py37_1000    conda-forge
pickleshare               0.7.5                 py37_1000    conda-forge
pillow                    5.4.1           py37h00a061d_1000    conda-forge
pip                       19.0.2                   py37_0    conda-forge
proj4                     5.2.0             h14c3975_1001    conda-forge
prometheus_client         0.5.0                      py_0    conda-forge
prompt_toolkit            2.0.8                      py_0    conda-forge
psutil                    5.5.0            py37h14c3975_0    conda-forge
pthread-stubs             0.4               h14c3975_1001    conda-forge
ptyprocess                0.6.0                 py37_1000    conda-forge
pycparser                 2.19                       py_0    conda-forge
pyepsg                    0.4.0                      py_0    conda-forge
pygments                  2.3.1                      py_0    conda-forge
pykdtree                  1.3.1           py37h3010b51_1002    conda-forge
pyopenssl                 19.0.0                   py37_0    conda-forge
pyparsing                 2.3.1                      py_0    conda-forge
pyproj                    1.9.6           py37hc0953d3_1000    conda-forge
pyqt                      5.6.0           py37h13b7fb3_1008    conda-forge
pyrsistent                0.14.10          py37h14c3975_0    conda-forge
pyshp                     2.0.1                      py_0    conda-forge
pysocks                   1.6.8                 py37_1002    conda-forge
python                    3.7.2                h0371630_0
python-cdo                1.4.0                      py_1    conda-forge
python-dateutil           2.8.0                      py_0    conda-forge
python-snappy             0.5.4            py37hee44bf9_0    conda-forge
pytz                      2018.9                     py_0    conda-forge
pyyaml                    3.13            py37h14c3975_1001    conda-forge
pyzmq                     17.1.2          py37h6afc9c9_1001    conda-forge
qt                        5.6.3                h8bf5577_3
readline                  7.0               hf8c457e_1001    conda-forge
requests                  2.21.0                py37_1000    conda-forge
ruamel                    1.0                      py37_0    conda-forge
ruamel.yaml               0.16.1           py37h516909a_0    conda-forge
s3fs                      0.3.3                    pypi_0    pypi
s3transfer                0.2.1                    pypi_0    pypi
scipy                     1.2.0           py37_blas_openblash1522bff_1201  [blas_openblas]  conda-forge
seaborn                   0.9.0                      py_0    conda-forge
send2trash                1.5.0                      py_0    conda-forge
setuptools                40.8.0                   py37_0    conda-forge
shapely                   1.6.4           py37h092830f_1002    conda-forge
sip                       4.18.1          py37hf484d3e_1000    conda-forge
six                       1.12.0                py37_1000    conda-forge
snappy                    1.1.7             he1b5a44_1002    conda-forge
sortedcontainers          2.1.0                      py_0    conda-forge
sqlite                    3.26.0            h67949de_1000    conda-forge
statsmodels               0.9.0           py37h3010b51_1000    conda-forge
tblib                     1.3.2                      py_1    conda-forge
terminado                 0.8.1                 py37_1001    conda-forge
testpath                  0.4.2                 py37_1000    conda-forge
tk                        8.6.9             h84994c4_1000    conda-forge
toolz                     0.9.0                      py_1    conda-forge
tornado                   5.1.1           py37h14c3975_1000    conda-forge
tqdm                      4.31.1                     py_0    conda-forge
traitlets                 4.3.2                 py37_1000    conda-forge
udunits2                  2.2.27.6          h4e0c4b3_1001    conda-forge
urllib3                   1.24.1                py37_1000    conda-forge
wcwidth                   0.1.7                      py_1    conda-forge
webencodings              0.5.1                      py_1    conda-forge
wheel                     0.32.3                   py37_0    conda-forge
xarray                    0.12.3                   pypi_0    pypi
xorg-libxau               1.0.8             h14c3975_1006    conda-forge
xorg-libxdmcp             1.1.2             h14c3975_1007    conda-forge
xz                        5.2.4             h14c3975_1001    conda-forge
yaml                      0.1.7             h14c3975_1001    conda-forge
zarr                      2.3.2                    py37_0    conda-forge
zeromq                    4.2.5             hf484d3e_1006    conda-forge
zict                      0.1.3                      py_0    conda-forge
zlib                      1.2.11            h14c3975_1004    conda-forge

</details>

**Comment by andersy005** [comment]
@aaronspring, 

As I pointed out in https://github.com/NCAR/intake-esm/issues/111#issuecomment-515180637, before we were parsing files according to the official CMIP DRS, and it became clear that not everybody's directory structure followed what is stated in the official DRS. As a result, we adopted a different structure for the YAML file used:

```yaml
name: GLADE-CMIP5
collection_type: cmip5
data_sources:
  CCCma-CanCM4-output:
    locations:
      - name: GLADE-CCCma-CanCM4-output
        loc_type: posix
        direct_access: True 
        urlpath: /glade/collections/cmip/cmip5/output/CCCma/CanCM4
        exclude_dirs: ['*/files/*', '*/latest/*']
        file_extension: .nc

    extra_attributes:
      product: output
      activity: CMIP5
      institute: CCCma

  MPI-M-MPI-ESM-LR-output1:
    locations:
      - name: GLADE-MPI-M-MPI-ESM-LR-output1
        loc_type: posix
        direct_access: True 
        urlpath: /glade/collections/cmip/cmip5/output1/MPI-M/MPI-ESM-LR
        exclude_dirs: ['*/files/*', '*/latest/*']
        file_extension: .nc

    extra_attributes:
      product: output1
      activity: CMIP5
     institute: MPI-M
```


From the conversation with @naomi-henderson, it became obvious that following the official DRS was the right thing to do. I am planning on reverting back to the old way of parsing CMIP data files in a future PR. 

For the time being, you might have to change your YAML file in order to have the latest intake-esm to work. Here's a full version of the YAML file we are using @ NCAR: https://github.com/NCAR/intake-esm-datastore/blob/master/collection-input/glade-cmip5-collection.yml

**Comment by aaronspring** [comment]
Thanks for the explanation. Could you maybe leave a short notice in the documentation about this?

It works now as I hoped except for https://github.com/NCAR/intake-esm/issues/76.

I liked the simplicity of just inputting a single path of the previous versions.
For implementing this new version, you generation gist really helped a lot: https://gist.github.com/andersy005/5cc53f9285ae6c0abb2ee573250b4ba9

**Comment by andersy005** [comment]
@aaronspring, 

> I liked the simplicity of just inputting a single path of the previous versions.

I am planning on opening a PR (sometime today or tomorrow) that will reinstitute this. I will ping you when it's ready
