### ISSUE TITLE
NorESM2-LM bug

### ISSUE THREAD

**Issue by fanchic** [NCAR/intake-esm#134]
Hey Guys,

When creating the catalog with the intake_esm_builder it seems that for one model only it interchanged source_id and experiment_id.

For this model source_id gives historical and experiment_id gives NorESM2-LM

/g/data/oi10/replicas/CMIP6/CMIP/NCC/NorESM2-LM/historical/r1i1p1f1/Amon/pr/gn/v20190815/pr_Amon_historical_NorESM2-LM_r1i1p1f1_gn_198001-198912.nc 

For all models like the following it works perfectly fine.

/g/data/oi10/replicas/CMIP6/CMIP/IPSL/IPSL-CM6A-LR/historical/r1i1p1f1/Amon/pr/gr/v20180803/pr_Amon_IPSL-CM6A-LR_historical_r1i1p1f1_gr_185001-201412.nc

Have any of you encounter issues with cataloging the submissions of the Norwegian model NorESM2-LM. Is that because of the file name structure ?

Cheers,

Francois

**Comment by andersy005** [comment]
@fanchic, 

I encountered a similar error with the NASA's GISS-E2-1 model a while ago:

```bash
$ ls /glade/collections/cmip/CMIP6/CMIP/NASA-GISS/GISS-E2-1-G/historical/r10i1p1f1/Lmon/evspsblveg/gn/v20181015/evspsblveg

evspsblveg_Lmon_GISS-E2-1-G_historical_r10i1p1f1_gn_185001-190012.nc  evspsblveg_Lmon_historical_GISS-E2-1-G_r10i1p1f1_gn_185001-190012.nc
evspsblveg_Lmon_GISS-E2-1-G_historical_r10i1p1f1_gn_190101-195012.nc  evspsblveg_Lmon_historical_GISS-E2-1-G_r10i1p1f1_gn_190101-195012.nc
evspsblveg_Lmon_GISS-E2-1-G_historical_r10i1p1f1_gn_195101-200012.nc  evspsblveg_Lmon_historical_GISS-E2-1-G_r10i1p1f1_gn_195101-200012.nc
evspsblveg_Lmon_GISS-E2-1-G_historical_r10i1p1f1_gn_200101-201412.nc  evspsblveg_Lmon_historical_GISS-E2-1-G_r10i1p1f1_gn_200101-201412.nc
```


In our case, we removed all CMIP6 files that exhibit the "swapped" source_id and experiment in the filename.  Each of these non CMIP6 DRS conforming files had a related correct and duplicate file, which was kept.


If you are unable to remove those corrupted files, you can this line in your YAML file and build the catalog again:

```YAML
exclude_dirs: ['*historical_NorESM2*']
```

For an example of what our yaml file, here's an [example](https://github.com/NCAR/intake-esm-datastore/blob/master/collection-input/glade-cmip6-collection.yml)

**Comment by andersy005** [comment]
This is an issue with the actual data. Closing this issue for the time being
