### ISSUE TITLE
Does extending collections only accept netCDF?

### ISSUE THREAD

**Issue by ahuang11** [NCAR/intake-esm#136]
I'm trying to extend my HDF5/binary collection, but it seems `'*.nc' `and `engine=netcdf4` is hardcoded, although I must admit I'm unfamiliar with how this package really works.

Under `bld_collection_utils.py`
```
def _get_built_collections():
    """Loads built collections in a dictionary with key=collection_name, value=collection_db_file_path"""
    try:
        db_dir = Path(config.get('database-directory'))
        cc = db_dir.glob('*.nc')
        collections = {}
        for f in cc:
            name = f.stem
            fullpath = f.absolute()
            collections[name] = fullpath
        return collections
    except Exception as e:
        raise e


def _open_collection(collection_name):
    """ Open an ESM collection"""
    collections = _get_built_collections()

    ds = xr.open_dataset(collections[collection_name], engine='netcdf4')
    ds['direct_access'] = ds['direct_access'].astype(bool)
    return ds
```

**Comment by ahuang11** [comment]
Nevermind, I feel like the catalog is stored as a `.nc`

**Comment by andersy005** [comment]
@ahuang11, this is going to change in the future. We recently decided to come up with an esm collection specification: https://github.com/NCAR/esm-collection-spec

With this new spec, the catalog is going to be a csv file instead of the netcdf
