### ISSUE TITLE
Replace KeyError exception message with a more informative one

### ISSUE THREAD

**Issue by ahuang11** [NCAR/intake-esm#141]
```
import intake

col = intake.open_esm_metadatastore(collection_name='nmme')
```

```
~/intake-esm/intake_esm/bld_collection_utils.py in _open_collection(collection_name)
    209     collections = _get_built_collections()
    210 
--> 211     ds = xr.open_dataset(collections[collection_name], engine='netcdf4')
    212     ds['direct_access'] = ds['direct_access'].astype(bool)
    213     return ds

KeyError: 'nmme'
```

I think it would be helpful to add a message to add a kwarg `overwrite_existing=True` or `rm ~/.intake_esm/config.yaml`, or "collection name does not exist in the persisted directory!" when someone encounters this error (primarily for people who is trying to extend a new dataset and experimenting with unfinalized paths)

**Comment by andersy005** [comment]
Closing this issue since this functionality was deprecated in #135
