### ISSUE TITLE
Pre-built collections don't get updated after yml paths/checksum is updated at remote repo

### ISSUE THREAD

**Issue by ahuang11** [NCAR/intake-esm#142]
When I updated my local intake-esm-datastore repo, and tried rebuilding my catalog, it only tried replacing the `.nc` collection, but did not try pulling the updated `.yml`

**Comment by ahuang11** [comment]
Nevermind, I think I forgot to update the checksum.

**Comment by ahuang11** [comment]
Actually, after my collection.nc was built and I updated my yml paths/checksum (pushed to repo), I'm wondering why it doesn't try re-building my collection.nc? Does it check the checksum after the collection is built?

**Comment by andersy005** [comment]
Closing this for the time being becuase this functionality isn't supported anymore
