### ISSUE TITLE
keyError on to_dataset_dict

### ISSUE THREAD

**Issue by pochedls** [NCAR/intake-esm#150]
### Description

I get key errors in calling to_dataset_dict

### Code

Running the following on cheyenne (via iPython):

```
# Imports
import intake
import pprint

# Parameters
var_ids = ['tas']
exp_ids = ['historical']

# Grab catalog data
col = intake.open_esm_datastore("catalogs/glade-cmip6.json")
cat = col.search(activity_id="CMIP", experiment_id=exp_ids,
                 variable_id=var_ids, table_id="Amon")
uni_dict = cat.unique(['source_id', 'experiment_id', 'table_id'])
pprint.pprint(uni_dict, compact=True)

dset_dict = cat.to_dataset_dict(zarr_kwargs={'consolidated': True, 'decode_times': False},
                                cdf_kwargs={'chunks': {}, 'decode_times': False})
```

I get the error message at bottom (note I've gotten different keyErrors using the same code, including for 'lat'). 

> .
> .
> .
> 
> /glade/work/pochedls/miniconda3/lib/python3.7/site-packages/xarray/core/utils.py in __getitem__(self, key)
>     382 
>     383     def __getitem__(self, key: K) -> V:
> --> 384         return self.mapping[key]
>     385 
>     386     def __iter__(self) -> Iterator[K]:
> 
> KeyError: 'j'

### Environment (base environment, probably a remnant of the environment created in the tutorial)

> (base) pochedls@cheyenne4:~/cmip6hack-pacific-sst> conda list                                                  
> packages in environment at /glade/work/pochedls/miniconda3:
> 
>  Name                    Version                   Build  Channel
> _libgcc_mutex             0.1                        main    defaults
> aiohttp                   3.6.1            py37h516909a_0    conda-forge
> appdirs                   1.4.3                      py_1    conda-forge
> asciitree                 0.3.3                      py_2    conda-forge
> asn1crypto                1.0.1                    py37_0    conda-forge
> async-timeout             3.0.1                   py_1000    conda-forge
> attrs                     19.2.0                     py_0    conda-forge
> backcall                  0.1.0                      py_0    conda-forge
> bash                      4.4.18            hcee41ef_1001    conda-forge
> bash_kernel               0.7.2                    py37_1    conda-forge
> bleach                    3.1.0                      py_0    conda-forge
> blinker                   1.4                        py_1    conda-forge
> bokeh                     1.3.4                    py37_0    conda-forge
> boto3                     1.9.250                    py_0    conda-forge
> botocore                  1.12.250                   py_0    conda-forge
> bzip2                     1.0.8                h516909a_1    conda-forge
> ca-certificates           2019.9.11            hecc5488_0    conda-forge
> cachetools                2.1.0                      py_0    conda-forge
> certifi                   2019.9.11                py37_0    conda-forge
> cffi                      1.12.3           py37h8022711_0    conda-forge
> cftime                    1.0.3.4         py37hd352d35_1001    conda-forge
> chardet                   3.0.4                 py37_1003    conda-forge
> click                     7.0                        py_0    conda-forge
> cloudpickle               1.2.2                      py_0    conda-forge
> conda                     4.7.12                   py37_0    conda-forge
> conda-package-handling    1.6.0            py37h516909a_0    conda-forge
> cryptography              2.7              py37h72c5cf5_0    conda-forge
> curl                      7.65.3               hf8cf82a_0    conda-forge
> cytoolz                   0.10.0           py37h516909a_0    conda-forge
> dask                      2.3.0                      py_0    conda-forge
> dask-core                 2.3.0                      py_0    conda-forge
> dask-labextension         1.0.3                      py_0    conda-forge
> decorator                 4.4.0                      py_0    conda-forge
> defusedxml                0.6.0                      py_0    conda-forge
> distributed               2.3.2                      py_1    conda-forge
> docutils                  0.15.2                   py37_0    conda-forge
> entrypoints               0.3                   py37_1000    conda-forge
> fasteners                 0.14.1                     py_3    conda-forge
> freetype                  2.10.0               he983fc9_1    conda-forge
> fsspec                    0.5.2                      py_0    conda-forge
> gcsfs                     0.3.1                      py_0    conda-forge
> google-auth               1.6.3                      py_0    conda-forge
> google-auth-oauthlib      0.4.1                      py_0    conda-forge
> hdf4                      4.2.13            h9a582f1_1002    conda-forge
> hdf5                      1.10.5          nompi_h3c11f04_1103    conda-forge
> heapdict                  1.0.1                      py_0    conda-forge
> icu                       64.2                 he1b5a44_1    conda-forge
> idna                      2.8                   py37_1000    conda-forge
> importlib_metadata        0.23                     py37_0    conda-forge
> intake                    0.5.3                      py_0    conda-forge
> intake-esm                2019.10.15                 py_0    conda-forge
> intake-xarray             0.3.1                      py_0    conda-forge
> ipykernel                 5.1.2            py37h5ca1d4c_0    conda-forge
> ipython                   7.8.0            py37h5ca1d4c_0    conda-forge
> ipython_genutils          0.2.0                      py_1    conda-forge
> ipywidgets                7.5.1                      py_0    conda-forge
> jedi                      0.15.1                   py37_0    conda-forge
> jinja2                    2.10.3                     py_0    conda-forge
> jmespath                  0.9.4                      py_0    conda-forge
> jpeg                      9c                h14c3975_1001    conda-forge
> json5                     0.8.5                      py_0    conda-forge
> jsonschema                3.1.1                    py37_0    conda-forge
> jupyter-server-proxy      1.1.0                      py_0    conda-forge
> jupyter_client            5.3.3                    py37_1    conda-forge
> jupyter_contrib_core      0.3.3                      py_2    conda-forge
> jupyter_contrib_nbextensions 0.5.1                    py37_0    conda-forge
> jupyter_core              4.5.0                      py_0    conda-forge
> jupyter_dashboards        0.7.0                 py37_1000    conda-forge
> jupyter_highlight_selected_word 0.2.0                 py37_1000    conda-forge
> jupyter_latex_envs        1.4.4                 py37_1000    conda-forge
> jupyter_nbextensions_configurator 0.4.1                    py37_0    conda-forge
> jupyterlab                1.1.4                      py_0    conda-forge
> jupyterlab_server         1.0.6                      py_0    conda-forge
> krb5                      1.16.3            h05b26f9_1001    conda-forge
> libblas                   3.8.0               13_openblas    conda-forge
> libcblas                  3.8.0               13_openblas    conda-forge
> libcurl                   7.65.3               hda55be3_0    conda-forge
> libedit                   3.1.20170329      hf8c457e_1001    conda-forge
> libffi                    3.2.1             he1b5a44_1006    conda-forge
> libgcc-ng                 9.1.0                hdf63c60_0    defaults
> libgfortran-ng            7.3.0                hdf63c60_2    conda-forge
> libiconv                  1.15              h516909a_1005    conda-forge
> liblapack                 3.8.0               13_openblas    conda-forge
> libnetcdf                 4.7.1           nompi_h94020b1_101    conda-forge
> libopenblas               0.3.7                h6e990d7_1    conda-forge
> libpng                    1.6.37               hed695b0_0    conda-forge
> libsodium                 1.0.17               h516909a_0    conda-forge
> libssh2                   1.8.2                h22169c7_2    conda-forge
> libstdcxx-ng              9.1.0                hdf63c60_0    defaults
> libtiff                   4.0.10            h57b8799_1003    conda-forge
> libuv                     1.32.0               h516909a_0    conda-forge
> libxml2                   2.9.9                hee79883_5    conda-forge
> libxslt                   1.1.33               h31b3aaa_0    conda-forge
> locket                    0.2.0                      py_2    conda-forge
> lxml                      4.4.1            py37h7ec2d77_0    conda-forge
> lz4-c                     1.8.3             he1b5a44_1001    conda-forge
> markupsafe                1.1.1            py37h14c3975_0    conda-forge
> mistune                   0.8.4           py37h14c3975_1000    conda-forge
> monotonic                 1.5                        py_0    conda-forge
> more-itertools            7.2.0                      py_0    conda-forge
> msgpack-numpy             0.4.4.3                    py_0    conda-forge
> msgpack-python            0.6.2            py37hc9558a2_0    conda-forge
> multidict                 4.5.2           py37h14c3975_1000    conda-forge
> nb_conda_kernels          2.2.2                    py37_0    conda-forge
> nbconvert                 5.6.0                    py37_1    conda-forge
> nbformat                  4.4.0                      py_1    conda-forge
> ncurses                   6.1               hf484d3e_1002    conda-forge
> netcdf4                   1.5.1.2          py37hf3213d6_2    conda-forge
> nodejs                    12.11.1              h10a4023_0    conda-forge
> notebook                  6.0.1                    py37_0    conda-forge
> numcodecs                 0.6.3            py37hf484d3e_0    conda-forge
> numpy                     1.17.2           py37h95a1406_0    conda-forge
> oauthlib                  3.0.1                      py_0    conda-forge
> olefile                   0.46                       py_0    conda-forge
> openssl                   1.1.1c               h516909a_0    conda-forge
> packaging                 19.2                       py_0    conda-forge
> pandas                    0.25.1           py37hb3f55d8_0    conda-forge
> pandoc                    2.7.3                         0    conda-forge
> pandocfilters             1.4.2                      py_1    conda-forge
> parso                     0.5.1                      py_0    conda-forge
> partd                     1.0.0                      py_0    conda-forge
> pexpect                   4.7.0                    py37_0    conda-forge
> pickleshare               0.7.5                 py37_1000    conda-forge
> pillow                    6.2.0            py37h6b7be26_0    conda-forge
> pip                       19.2.3                   py37_0    conda-forge
> prometheus_client         0.7.1                      py_0    conda-forge
> prompt_toolkit            2.0.10                     py_0    conda-forge
> psutil                    5.6.3            py37h516909a_0    conda-forge
> ptyprocess                0.6.0                   py_1001    conda-forge
> pyasn1                    0.4.6                      py_0    conda-forge
> pyasn1-modules            0.2.7                      py_0    conda-forge
> pycosat                   0.6.3           py37h14c3975_1001    conda-forge
> pycparser                 2.19                     py37_1    conda-forge
> pygments                  2.4.2                      py_0    conda-forge
> pyjwt                     1.7.1                      py_0    conda-forge
> pyopenssl                 19.0.0                   py37_0    conda-forge
> pyparsing                 2.4.2                      py_0    conda-forge
> pyrsistent                0.15.4           py37h516909a_0    conda-forge
> pysocks                   1.7.1                    py37_0    conda-forge
> python                    3.7.3                h33d41f4_1    conda-forge
> python-dateutil           2.8.0                      py_0    conda-forge
> python-snappy             0.5.4            py37hee44bf9_0    conda-forge
> pytz                      2019.3                     py_0    conda-forge
> pyyaml                    5.1.2            py37h516909a_0    conda-forge
> pyzmq                     18.1.0           py37h1768529_0    conda-forge
> readline                  8.0                  hf8c457e_0    conda-forge
> requests                  2.22.0                   py37_1    conda-forge
> requests-oauthlib         1.2.0                      py_0    conda-forge
> rsa                       3.4.2                      py_1    conda-forge
> ruamel.yaml               0.16.5           py37h516909a_1    conda-forge
> ruamel.yaml.clib          0.2.0            py37h516909a_0    conda-forge
> ruamel_yaml               0.15.71         py37h14c3975_1000    conda-forge
> s3fs                      0.3.5                      py_0    conda-forge
> s3transfer                0.2.1                    py37_0    conda-forge
> send2trash                1.5.0                      py_0    conda-forge
> setuptools                41.4.0                   py37_0    conda-forge
> simpervisor               0.3                        py_1    conda-forge
> six                       1.12.0                py37_1000    conda-forge
> snappy                    1.1.7             he1b5a44_1002    conda-forge
> sortedcontainers          2.1.0                      py_0    conda-forge
> sqlite                    3.30.1               hcee41ef_0    conda-forge
> tblib                     1.4.0                      py_0    conda-forge
> terminado                 0.8.2                    py37_0    conda-forge
> testpath                  0.4.2                   py_1001    conda-forge
> tk                        8.6.9             hed695b0_1003    conda-forge
> toolz                     0.10.0                     py_0    conda-forge
> tornado                   6.0.3            py37h516909a_0    conda-forge
> tqdm                      4.36.1                     py_0    conda-forge
> traitlets                 4.3.3                    py37_0    conda-forge
> urllib3                   1.25.6                   py37_0    conda-forge
> wcwidth                   0.1.7                      py_1    conda-forge
> webencodings              0.5.1                      py_1    conda-forge
> wheel                     0.33.6                   py37_0    conda-forge
> widgetsnbextension        3.5.1                    py37_0    conda-forge
> xarray                    0.14.0                     py_0    conda-forge
> xz                        5.2.4             h14c3975_1001    conda-forge
> yaml                      0.1.7             h14c3975_1001    conda-forge
> yarl                      1.3.0           py37h14c3975_1000    conda-forge
> zarr                      2.3.2                    py37_0    conda-forge
> zeromq                    4.3.2                he1b5a44_2    conda-forge
> zict                      1.0.0                      py_0    conda-forge
> zipp                      0.6.0                      py_0    conda-forge
> zlib                      1.2.11            h516909a_1006    conda-forge
> zstd                      1.4.0                h3b9ef0a_0    conda-forge

**Comment by matt-long** [comment]
I was able to avoid this error by reversing the order of operations in the `aggregations` specified in the JSON file. This would likely resolve #151 too.

```json
{
  "esmcat_version": "0.1.0",
  "id": "glade-cmip6",
  "description": "This is an ESM collection for CMIP6 data accessible on the NCAR's GLADE disk storage system in /glade/collections/cmip/CMIP6",
  "catalog_file": "/glade/collections/cmip/catalog/intake-esm-datastore/catalogs/glade-cmip6.csv.gz",
  "attributes": [
    {
      "column_name": "activity_id",
      "vocabulary": "https://raw.githubusercontent.com/WCRP-CMIP/CMIP6_CVs/master/CMIP6_activity_id.json"
    },
    {
      "column_name": "source_id",
      "vocabulary": "https://raw.githubusercontent.com/WCRP-CMIP/CMIP6_CVs/master/CMIP6_source_id.json"
    },
    {
      "column_name": "institution_id",
      "vocabulary": "https://raw.githubusercontent.com/WCRP-CMIP/CMIP6_CVs/master/CMIP6_institution_id.json"
    },
    {
      "column_name": "experiment_id",
      "vocabulary": "https://raw.githubusercontent.com/WCRP-CMIP/CMIP6_CVs/master/CMIP6_experiment_id.json"
    },
    { "column_name": "member_id", "vocabulary": "" },
    {
      "column_name": "table_id",
      "vocabulary": "https://raw.githubusercontent.com/WCRP-CMIP/CMIP6_CVs/master/CMIP6_table_id.json"
    },
    { "column_name": "variable_id", "vocabulary": "" },
    {
      "column_name": "grid_label",
      "vocabulary": "https://raw.githubusercontent.com/WCRP-CMIP/CMIP6_CVs/master/CMIP6_grid_label.json"
    },
    {
      "column_name": "version",
      "vocabulary": ""
    },
    {
      "column_name": "dcpp_start_year",
      "vocabulary": ""
    }         
  ],
  "assets": {
    "column_name": "path",
    "format": "netcdf"
  },
  "aggregation_control": {
    "variable_column_name": "variable_id",
    "groupby_attrs": [
      "activity_id",
      "institution_id",
      "source_id",
      "experiment_id",
      "table_id",
      "grid_label"
    ],
    "aggregations": [
      {
        "type": "union",
        "attribute_name": "variable_id"
      },        
      {
        "type": "join_existing",
        "attribute_name": "time_range",
        "options": { "dim": "time", "coords": "minimal", "compat": "override" }
      },
      {
        "type": "join_new",
        "attribute_name": "member_id",
        "options": { "coords": "minimal", "compat": "override" }
      },
    {
        "type": "join_new",
        "attribute_name": "dcpp_init_year",
        "options": { "coords": "minimal", "compat": "override" }
      } 
    ]
  }
}
```

cc @andersy005

**Comment by andersy005** [comment]
I can confirm that this is fixed. @pochedls, can you update the collection json files with respective file content from https://github.com/cmip6hack/project-template/tree/master/catalogs and let us know whether this is still an issue for you?

**Comment by dcherian** [comment]
Is this an xarray bug?

**Comment by andersy005** [comment]
I am reopening this since it appears to be related to #169

**Comment by andersy005** [comment]
@dcherian, 

> Is this an xarray bug?

So far, I believe this issue has to do with our order of operations and not an xarray bug. I am looking into this in #169 and will let you know.

**Comment by andersy005** [comment]
With #171, the issue seems to be fixed. 

```python
import intake
col = intake.open_esm_datastore("/glade/collections/cmip/catalog/intake-esm-datastore/catalogs/glade-cmip6.json")
cat = col.search(activity_id="CMIP", experiment_id="historical", variable_id="tas", table_id="Amon")
```

However, I am noticing some discrepancies in the time axis length for different models. For instance (`CMIP.CAS.FGOALS-g3.historical.Amon.gn`, `CMIP.NOAA-GFDL.GFDL-ESM4.historical.Amon.gr1`):

```python
dsets = cat.to_dataset_dict(cdf_kwargs={"chunks": {"time": 36}})
for key, ds in dsets.items():
    print(f"{key}")
    print(f"\t{ds.dims}")
```

```python
CMIP.BCC.BCC-CSM2-MR.historical.Amon.gn
	Frozen(SortedKeysDict({'lon': 320, 'bnds': 2, 'time': 1980, 'lat': 160, 'member_id': 3}))
CMIP.BCC.BCC-ESM1.historical.Amon.gn
	Frozen(SortedKeysDict({'lon': 128, 'bnds': 2, 'time': 1980, 'lat': 64, 'member_id': 3}))
CMIP.CAMS.CAMS-CSM1-0.historical.Amon.gn
	Frozen(SortedKeysDict({'lon': 320, 'bnds': 2, 'time': 1980, 'lat': 160, 'member_id': 1}))
CMIP.CAS.FGOALS-g3.historical.Amon.gn
	Frozen(SortedKeysDict({'lon': 180, 'bnds': 2, 'time': 2004, 'lat': 80, 'member_id': 3}))
CMIP.CCCma.CanESM5.historical.Amon.gn
	Frozen(SortedKeysDict({'lon': 128, 'bnds': 2, 'time': 1980, 'lat': 64, 'member_id': 49}))
CMIP.CNRM-CERFACS.CNRM-CM6-1.historical.Amon.gr
	Frozen(SortedKeysDict({'time': 1980, 'axis_nbounds': 2, 'lon': 256, 'lat': 128, 'member_id': 15}))
CMIP.CNRM-CERFACS.CNRM-ESM2-1.historical.Amon.gr
	Frozen(SortedKeysDict({'time': 1980, 'axis_nbounds': 2, 'lon': 256, 'lat': 128, 'member_id': 5}))
CMIP.E3SM-Project.E3SM-1-0.historical.Amon.gr
	Frozen(SortedKeysDict({'lon': 360, 'bnds': 2, 'time': 1980, 'lat': 180, 'member_id': 5}))
CMIP.EC-Earth-Consortium.EC-Earth3.historical.Amon.gr
	Frozen(SortedKeysDict({'j': 256, 'i': 512, 'time': 1981, 'bnds': 2, 'vertices': 4, 'lat': 514, 'lon': 512, 'member_id': 12}))
CMIP.EC-Earth-Consortium.EC-Earth3-Veg.historical.Amon.gr
	Frozen(SortedKeysDict({'lon': 512, 'bnds': 2, 'time': 1980, 'lat': 258, 'member_id': 4}))
CMIP.IPSL.IPSL-CM6A-LR.historical.Amon.gr
	Frozen(SortedKeysDict({'time': 1980, 'axis_nbounds': 2, 'lon': 144, 'lat': 143, 'member_id': 32}))
CMIP.MIROC.MIROC-ES2L.historical.Amon.gn
	Frozen(SortedKeysDict({'lon': 128, 'bnds': 2, 'time': 1980, 'lat': 64, 'member_id': 3}))
CMIP.MIROC.MIROC6.historical.Amon.gn
	Frozen(SortedKeysDict({'lon': 256, 'bnds': 2, 'time': 1980, 'lat': 128, 'member_id': 10}))
CMIP.MOHC.HadGEM3-GC31-LL.historical.Amon.gn
	Frozen(SortedKeysDict({'lon': 192, 'bnds': 2, 'time': 1980, 'lat': 144, 'member_id': 4}))
CMIP.MOHC.UKESM1-0-LL.historical.Amon.gn
	Frozen(SortedKeysDict({'lon': 192, 'bnds': 2, 'time': 1980, 'lat': 144, 'member_id': 9}))
CMIP.MRI.MRI-ESM2-0.historical.Amon.gn
	Frozen(SortedKeysDict({'lon': 320, 'bnds': 2, 'time': 1980, 'lat': 160, 'member_id': 5}))
CMIP.NASA-GISS.GISS-E2-1-G.historical.Amon.gn
	Frozen(SortedKeysDict({'lon': 144, 'bnds': 2, 'time': 1980, 'lat': 90, 'member_id': 22}))
CMIP.NASA-GISS.GISS-E2-1-H.historical.Amon.gn
	Frozen(SortedKeysDict({'lon': 144, 'bnds': 2, 'time': 1980, 'lat': 90, 'member_id': 10}))
CMIP.NCAR.CESM2.historical.Amon.gn
	Frozen(SortedKeysDict({'lon': 288, 'nbnd': 2, 'time': 1980, 'lat': 192, 'member_id': 11}))
CMIP.NCAR.CESM2-WACCM.historical.Amon.gn
	Frozen(SortedKeysDict({'lon': 288, 'nbnd': 2, 'time': 1980, 'lat': 192, 'member_id': 3}))
CMIP.NCC.NorESM2-LM.historical.Amon.gn
	Frozen(SortedKeysDict({'lon': 144, 'bnds': 2, 'time': 1980, 'lat': 96, 'member_id': 3}))
CMIP.NOAA-GFDL.GFDL-CM4.historical.Amon.gr1
	Frozen(SortedKeysDict({'lon': 288, 'bnds': 2, 'time': 1980, 'lat': 180, 'member_id': 1}))
CMIP.NOAA-GFDL.GFDL-ESM4.historical.Amon.gr1
	Frozen(SortedKeysDict({'lon': 288, 'bnds': 2, 'time': 780, 'lat': 180, 'member_id': 1}))
CMIP.NUIST.NESM3.historical.Amon.gn
	Frozen(SortedKeysDict({'lon': 192, 'bnds': 2, 'time': 1980, 'lat': 96, 'member_id': 5}))
CMIP.SNU.SAM0-UNICON.historical.Amon.gn
	Frozen(SortedKeysDict({'lon': 288, 'bnds': 2, 'time': 1980, 'lat': 192, 'member_id': 1}))
```

I haven't looked into these inconsistencies in the data yet!
