### ISSUE TITLE
Issue with loading catalog entries into a dictionary of xarray datasets

### ISSUE THREAD

**Issue by PMongwe** [NCAR/intake-esm#151]
384         return self.mapping[key]
    385 
    386     def __iter__(self) -> Iterator[K]:

KeyError: 'depth'
>>>>>>>>>>>>>>>>>>>>>>>>>>>

**Comment by andersy005** [comment]
There might be some connection between this issue and #169. I am currently investigating this

**Comment by andersy005** [comment]
Addressed over in #171
