### ISSUE TITLE
to_dataset_dict not setting time.encoding when decode_times=True

### ISSUE THREAD

**Issue by klindsay28** [NCAR/intake-esm#153]
It looks like `time.encoding` is not being set when I read in multiple files with `to_dataset_dict` with `decode_times=True`.

When you write a dataset to netCDF with no time encoding, the resulting time units end up differing from the original datasets, which I find to be unexpected behavior.

Following pydata/xarray#1614, a potential behavior is to keep the encoding from the first file. I think this is already being done for attributes.

**Comment by andersy005** [comment]
@klindsay28, when you get time, can you try the master branch

```bash
pip install git+https://github.com/NCAR/intake-esm.git
```

and confirm that this is working properly?

**Comment by klindsay28** [comment]
@andersy005, this update appears to be working.

I spot checked a couple of CMIP6 datasets for which `to_dataset_dict` was previously not setting `time.encoding`, and `time.encoding` is being set with the updated intake_esm.

Thanks!
