### ISSUE TITLE
Extract catalog entries by key

### ISSUE THREAD

**Issue by jhamman** [NCAR/intake-esm#165]
In vanilla Intake and Intake-xarray, users access datasets through the Entry class and the `to_dask` (or `to_xarray`), e.g:

```python
import intake
cat = intake.open_catalog('catalog.yml')
cat['key1'].to_dask()
```

Or for nested catalogs, 

```python
cat['key1.key2'].to_dask()
```

It would be nice if single aggregated datasets can be accessed in the same pattern:

```python
cat['CMIP.CCCma.CanESM5.historical.Ofx.gn'].to_xarray()
# is equivalent to
cat.to_datasets_dict(...)['CMIP.CCCma.CanESM5.historical.Ofx.gn']
```

It may be worth thinking about using the Entry class more explicitly to allow for more intake-like behavior in this way.

**Comment by jhamman** [comment]
@andersy005 - do you have thoughts on if/how this should be done?

I think the target implementation implementation should include:

1. Addition basic dict methods (e.g. `keys()`, `__len__()`, `__getitem__()` )
2. `__getitem__` returns `Entry` objects
3. `__getitem__` accepts full and partial keys. 
    - Full key (e.g. `'CMIP.CCCma.CanESM5.historical.Ofx.gn' == '.'.join(cat.df.iloc[0].to_list()[:-2])`)  returns a single Entry
    - Partial key (e.g. `CMIP.CCCma.CanESM5.historical.Ofx`) returns a new catalog subselected to match provided keys.
4. Abstract aggregate Entry. This would essentially provide the functionality used in the current `to_dataset_dict()`.
    - `cat.aggregate()` would return a new catalog (probably a new class) with Entry objects that included a mergable set of datasets (one key per set)
    - this would allow users to opt in to aggregation/merging while still providing catalog functionality for individual datasets.

**Comment by andersy005** [comment]
@jhamman 

> @andersy005 - do you have thoughts on if/how this should be done?

I haven't looked into this yet. However, I'm about to start playing with the Entry class approach. I will let you know how it goes, and will ping you when I need help
