### ISSUE TITLE
module 'intake' has no attribute 'open_esm_datastore'

### ISSUE THREAD

**Issue by ChunchengGuo** [NCAR/intake-esm#170]
Hi, I opened a jupyter notebook on https://ocean.pangeo.io, and when running -

import intake
col = intake.open_esm_datastore("./pangeo-cmip6.json")
col

I got the following error -

module 'intake' has no attribute 'open_esm_datastore'

It has the attribute open_esm_metadatastore though (not sure if that's relevant). "intake.open_esm_datastore" works well on my local laptop.

any idea what the issue could be here? :)

Thanks!
Chuncheng

**Comment by andersy005** [comment]
@ChunchengGuo,

Can you confirm that you have intake-esm installed in your conda environment by running

```bash
conda list intake-esm
```
?

**Comment by ChunchengGuo** [comment]
@andersy005 
yes, it is installed, e.g. -

(notebook) jovyan@jupyter-0000-2d0001-2d6276-2d6499:~$ conda list intake-esm
# packages in environment at /srv/conda/envs/notebook:
#
# Name                    Version                   Build  Channel
intake-esm                2019.8.23                  py_0    conda-forge

**Comment by andersy005** [comment]
That version is an old version of intake-esm. You need to update to the latest version (2019.10.15) or the from the master branch:

```bash
conda install intake-esm==2019.10.15
```

or 

```bash
python -m pip install intake-esm --upgrade
```

or 

```bash
python -m pip install git+https://github.com/NCAR/intake-esm.git
```

**Comment by ChunchengGuo** [comment]
ah, yes..
I somehow overlooked that when 'conda search'
it works now; thanks @andersy005!
