### ISSUE TITLE
File paths from intake-ism query 

### ISSUE THREAD

**Issue by EricKeenan** [NCAR/intake-esm#178]
Does intake-esm have an option to display the path where files came from?

**Comment by andersy005** [comment]
@EricKeenan, 

```python
paths = col.df[col._col_data['assets']["column_name"]].tolist()
```


will give you a list of paths.

Does this option provide what you are looking for?

**Comment by EricKeenan** [comment]
@andersy005 Yes, this was exactly what I need! Thank you for the quick reply. 

Closing this issue now (first time was an accident).
