### ISSUE TITLE
collection search with dictionary

### ISSUE THREAD

**Issue by lvankampenhout** [NCAR/intake-esm#188]
Currently, to search a collection one has to write:
```
cat = col.search(experiment_id='historical', table_id='Amon', variable_id='tas', activity_id='CMIP')
```

Yet different collections have different column naming conventions. For instance the CMIP6 collection on glade has a column called `institution_id` whereas in the CMIP5 collection this is called `institute`. 

It would therefore be nice to generalize the above search call by passing a dictionary:

```
cat = col.search( {'experiment_id' : 'historical', 'table_id':'Amon', 'variable_id':'tas', 'activity_id':'CMIP'} )
```
where the keys in the dictionary can be made dependent on the collection one is using. 

With the current call interface, the only way to achieve this is by using `eval()` which is cumbersome to use.

**Comment by lvankampenhout** [comment]
A current workaround is to use wrapper functions

```

def collection_search_cmip5(col, model=None, experiment=None, variable=None, table=None, member=None):
    return col.search(model=model, experiment=experiment, variable=variable, mip_table=table,
                     ensemble_member=member)
    
def collection_search_cmip6(col, model=None, experiment=None, variable=None, table=None, member=None):
    return col.search(source_id=model, experiment_id=experiment, variable_id=variable, table_id=table,
                     member_id=member)

collection = 'CMIP5'

if collection == 'CMIP5': 
    collection_search = collection_search_cmip5
elif collection == 'CMIP6':
    collection_search = collection_search_cmip6
```

**Comment by andersy005** [comment]
@lvankampenhout, if your query is expressed as a dictionary, you can `unpack` it when calling `search()` method:

```python
In [1]: import intake                                                                                                 

In [2]: url = "https://raw.githubusercontent.com/NCAR/intake-esm-datastore/master/catalogs/pangeo-cmip6.json"         

In [3]: col = intake.open_esm_datastore(url)      
In [6]: query = {"source_id" : ['BCC-CSM2-MR', 'CNRM-CM6-1', 'CNRM-ESM2-1'], "table_id": "Amon"}                      

In [7]: col_sub = col.search(**query) 
```

Notice the `**` in front of the dictionary. The `**` is what does the ["unpacking"](https://thispointer.com/python-how-to-unpack-list-tuple-or-dictionary-to-function-arguments-using/)

> It would therefore be nice to generalize the above search call by passing a dictionary:

This is already the case. `search()` is dynamic in that it is not tied to any collection. It expects keyword arguments which can be expressed as dictionary as shown above:

https://github.com/NCAR/intake-esm/blob/9f3f87caaec96bf482fdd67853f0105d7637f4c2/intake_esm/core.py#L92

**Comment by lvankampenhout** [comment]
@andersy005 thanks for your response. The unpacking of the dictionary is a great solution I did not realize exists! Thanks again.
