### ISSUE TITLE
Support coordinate alignment on merge

### ISSUE THREAD

**Issue by matt-long** [NCAR/intake-esm#197]
We used to align coords prior to merge operations. It would be nice to reimplement this feature.

**Comment by dcherian** [comment]
What does this mean? Ignoring floating point differences in coordinate values?

**Comment by matt-long** [comment]
We used to do an `xr.align` step to account for situations where, for instance, not all dataset had a time axis of the same temporal extent. This may be happening automatically in xarray now, however, so this issue may be out of date.

**Comment by dcherian** [comment]
``` python
dset_dict = cat.to_dataset_dict(
    zarr_kwargs={"consolidated": True, "decode_times": True},
    cdf_kwargs={"chunks": {}, "decode_times": True},
)
```

Why is it useful to make all datasets in `dset_dict` aligned in time when the models can have very different time-extents? 

xarray should automatically align them when necessary i.e. when you try to calculate something?

**Comment by matt-long** [comment]
The collection of datasets in `dset_dict` should not be aligned, rather each of these is typically constructed from contributing datasets. In the CESM-LE, for instance, ensemble 001, historical, has a time axis from 1850-2005 while the other members have time axes 1920-2005. `dset_dict` might have a key `ocn.pop.h.20C` (or whatever) and that dataset may have an ensemble dimension generated by `intake-esm` ("join_new"). It is at this level that I was concerned that alignment must be applied to properly join the disparate time axes. 

As I said above, however, xarray may be handling this for us now.

**Comment by andersy005** [comment]
Sounds like this is not needed anymore. Is it okay to close this?

**Comment by dcherian** [comment]
> that dataset may have an ensemble dimension generated by intake-esm ("join_new").

Datasets are always aligned, so IIUC this can be closed.

**Comment by andersy005** [comment]
Thank you, @dcherian! Closing...
