### ISSUE TITLE
More detailed debugging information?

### ISSUE THREAD

**Issue by jbusecke** [NCAR/intake-esm#206]
I am currently trying to diagnose a problem I encountered when using `cmip6_preprocessing`:

```
import intake
from cmip6_preprocessing.preprocessing import combined_preprocessing

col = intake.open_esm_datastore("https://raw.githubusercontent.com/NCAR/intake-esm-datastore/master/catalogs/pangeo-cmip6.json")
experiment_ids = ['historical']
query = dict(variable_id=['thetao']
             experiment_id=experiment_ids,
             table_id=['Omon'])
cat = col.search(**query)
data_dict = cat.to_dataset_dict(zarr_kwargs={'consolidated': True, 'decode_times':True})
```
This works without errors, but when I add the preprocessing, I get an error:

```
data_dict_new = cat.to_dataset_dict(zarr_kwargs={'consolidated': True, 'decode_times':True}, preprocess=combined_preprocessing)
```

<details>
Progress: |█████████████████████████████--------------------------------------------------| 37.0% MIROC-ES2L: No units found
MIROC6: No units found
Progress: |██████████████████████████████████---------------------------------------------| 43.5% MIROC6: No units found
MIROC-ES2L: No units found
CESM2-FV2: Unexpected unit (centimeters) for coordinate `lev` detected.
	 Converted to `m`
Progress: |█████████████████████████████████████████--------------------------------------| 52.2% CESM2-WACCM-FV2: Unexpected unit (centimeters) for coordinate `lev` detected.
	 Converted to `m`
Progress: |█████████████████████████████████████████████----------------------------------| 56.5% CESM2: Unexpected unit (centimeters) for coordinate `lev` detected.
	 Converted to `m`
MIROC6: No units found
CESM2-WACCM: Unexpected unit (centimeters) for coordinate `lev` detected.
	 Converted to `m`
MIROC-ES2L: No units found
Progress: |████████████████████████████████████████████████-------------------------------| 60.9% MIROC6: No units found
Progress: |████████████████████████████████████████████████████---------------------------| 65.2% MIROC6: No units found
Progress: |██████████████████████████████████████████████████████████---------------------| 73.9% MIROC6: No units found
CESM2: Unexpected unit (centimeters) for coordinate `lev` detected.
	 Converted to `m`
MIROC6: No units found
Progress: |██████████████████████████████████████████████████████████████-----------------| 78.3% MIROC6: No units found
Progress: |████████████████████████████████████████████████████████████████---------------| 80.4% MIROC6: No units found
MIROC6: No units found
Progress: |█████████████████████████████████████████████████████████████████--------------| 82.6% CESM2: Unexpected unit (centimeters) for coordinate `lev` detected.
	 Converted to `m`
Progress: |█████████████████████████████████████████████████████████████████████----------| 87.0% CESM2: Unexpected unit (centimeters) for coordinate `lev` detected.
	 Converted to `m`
Progress: |████████████████████████████████████████████████████████████████████████-------| 91.3% CESM2: Unexpected unit (centimeters) for coordinate `lev` detected.
	 Converted to `m`
CESM2: Unexpected unit (centimeters) for coordinate `lev` detected.
	 Converted to `m`
CESM2: Unexpected unit (centimeters) for coordinate `lev` detected.
	 Converted to `m`
CESM2: Unexpected unit (centimeters) for coordinate `lev` detected.
	 Converted to `m`
CESM2: Unexpected unit (centimeters) for coordinate `lev` detected.
	 Converted to `m`
CESM2: Unexpected unit (centimeters) for coordinate `lev` detected.
	 Converted to `m`
CESM2: Unexpected unit (centimeters) for coordinate `lev` detected.
	 Converted to `m`
Progress: |████████████████████████████████████████████████████████████████████████████---| 95.7% 
---------------------------------------------------------------------------
InvalidIndexError                         Traceback (most recent call last)
<ipython-input-18-a886fa917475> in <module>
      1 # Huh this also works. So it seems that the preprocessing messes something up prior to aggregation. Is this due to time?
----> 2 data_dict_new = cat.to_dataset_dict(zarr_kwargs={'consolidated': True, 'decode_times':True}, preprocess=combined_preprocessing)

/srv/conda/envs/notebook/lib/python3.7/site-packages/intake_esm/core.py in to_dataset_dict(self, zarr_kwargs, cdf_kwargs, preprocess, aggregate, storage_options)
    385         self.preprocess = preprocess
    386 
--> 387         return self._open_dataset()
    388 
    389     def _open_dataset(self):

/srv/conda/envs/notebook/lib/python3.7/site-packages/intake_esm/core.py in _open_dataset(self)
    471 
    472             for i, task in enumerate(futures.as_completed(future_tasks)):
--> 473                 result = task.result()
    474                 dsets.append(result)
    475                 if self.progressbar:

/srv/conda/envs/notebook/lib/python3.7/concurrent/futures/_base.py in result(self, timeout)
    426                 raise CancelledError()
    427             elif self._state == FINISHED:
--> 428                 return self.__get_result()
    429 
    430             self._condition.wait(timeout)

/srv/conda/envs/notebook/lib/python3.7/concurrent/futures/_base.py in __get_result(self)
    382     def __get_result(self):
    383         if self._exception:
--> 384             raise self._exception
    385         else:
    386             return self._result

/srv/conda/envs/notebook/lib/python3.7/concurrent/futures/thread.py in run(self)
     55 
     56         try:
---> 57             result = self.fn(*self.args, **self.kwargs)
     58         except BaseException as exc:
     59             self.future.set_exception(exc)

/srv/conda/envs/notebook/lib/python3.7/site-packages/intake_esm/core.py in _load_group_dataset(key, df, col_data, agg_columns, aggregation_dict, path_column_name, variable_column_name, use_format_column, mapper_dict, zarr_kwargs, cdf_kwargs, preprocess)
    560         zarr_kwargs,
    561         cdf_kwargs,
--> 562         preprocess,
    563     )
    564 

/srv/conda/envs/notebook/lib/python3.7/site-packages/intake_esm/merge_util.py in _aggregate(aggregation_dict, agg_columns, n_agg, v, lookup, mapper_dict, zarr_kwargs, cdf_kwargs, preprocess)
    162             return ds
    163 
--> 164     return apply_aggregation(v)
    165 
    166 

/srv/conda/envs/notebook/lib/python3.7/site-packages/intake_esm/merge_util.py in apply_aggregation(v, agg_column, key, level)
    109             dsets = [
    110                 apply_aggregation(value, agg_column, key=key, level=level + 1)
--> 111                 for key, value in v.items()
    112             ]
    113             keys = list(v.keys())

/srv/conda/envs/notebook/lib/python3.7/site-packages/intake_esm/merge_util.py in <listcomp>(.0)
    109             dsets = [
    110                 apply_aggregation(value, agg_column, key=key, level=level + 1)
--> 111                 for key, value in v.items()
    112             ]
    113             keys = list(v.keys())

/srv/conda/envs/notebook/lib/python3.7/site-packages/intake_esm/merge_util.py in apply_aggregation(v, agg_column, key, level)
    140                     coord_value=keys,
    141                     varname=varname,
--> 142                     options=agg_options,
    143                 )
    144 

/srv/conda/envs/notebook/lib/python3.7/site-packages/intake_esm/merge_util.py in join_new(dsets, dim_name, coord_value, varname, options)
     15     except Exception as e:
     16         logger.error(f'Failed to join datasets along new dimension.')
---> 17         raise e
     18 
     19 

/srv/conda/envs/notebook/lib/python3.7/site-packages/intake_esm/merge_util.py in join_new(dsets, dim_name, coord_value, varname, options)
     12     try:
     13         concat_dim = xr.DataArray(coord_value, dims=(dim_name), name=dim_name)
---> 14         return xr.concat(dsets, dim=concat_dim, data_vars=varname, **options)
     15     except Exception as e:
     16         logger.error(f'Failed to join datasets along new dimension.')

/srv/conda/envs/notebook/lib/python3.7/site-packages/xarray/core/concat.py in concat(objs, dim, data_vars, coords, compat, positions, fill_value, join)
    131             "objects, got %s" % type(first_obj)
    132         )
--> 133     return f(objs, dim, data_vars, coords, compat, positions, fill_value, join)
    134 
    135 

/srv/conda/envs/notebook/lib/python3.7/site-packages/xarray/core/concat.py in _dataset_concat(datasets, dim, data_vars, coords, compat, positions, fill_value, join)
    299     datasets = [ds.copy() for ds in datasets]
    300     datasets = align(
--> 301         *datasets, join=join, copy=False, exclude=[dim], fill_value=fill_value
    302     )
    303 

/srv/conda/envs/notebook/lib/python3.7/site-packages/xarray/core/alignment.py in align(join, copy, indexes, exclude, fill_value, *objects)
    296                 if join == "exact":
    297                     raise ValueError(f"indexes along dimension {dim!r} are not equal")
--> 298                 index = joiner(matching_indexes)
    299                 joined_indexes[dim] = index
    300             else:

/srv/conda/envs/notebook/lib/python3.7/site-packages/pandas/core/indexes/base.py in __or__(self, other)
   2383 
   2384     def __or__(self, other):
-> 2385         return self.union(other)
   2386 
   2387     def __xor__(self, other):

/srv/conda/envs/notebook/lib/python3.7/site-packages/pandas/core/indexes/base.py in union(self, other, sort)
   2517             return self._union_incompatible_dtypes(other, sort=sort)
   2518 
-> 2519         return self._union(other, sort=sort)
   2520 
   2521     def _union(self, other, sort):

/srv/conda/envs/notebook/lib/python3.7/site-packages/pandas/core/indexes/numeric.py in _union(self, other, sort)
    161             return first._union(second, sort)
    162         else:
--> 163             return super()._union(other, sort)
    164 
    165 

/srv/conda/envs/notebook/lib/python3.7/site-packages/pandas/core/indexes/base.py in _union(self, other, sort)
   2566                 result.extend([x for x in rvals if x not in value_set])
   2567         else:
-> 2568             indexer = self.get_indexer(other)
   2569             indexer, = (indexer == -1).nonzero()
   2570 

/srv/conda/envs/notebook/lib/python3.7/site-packages/pandas/core/indexes/base.py in get_indexer(self, target, method, limit, tolerance)
   2983         if not self.is_unique:
   2984             raise InvalidIndexError(
-> 2985                 "Reindexing only valid with uniquely" " valued Index objects"
   2986             )
   2987 

InvalidIndexError: Reindexing only valid with uniquely valued Index objects

</details>

I am pretty sure this is due to a certain model (usual candidates are CanESM5 and IPSL), but it is hard to diagnose where this error is occurring during the aggregation. Would it be possible to have an `ultra_verbose` mode for `.to_dataset_dict()', which lists the parameters of the datasets which are currently aggregated?

Side note: I tried to rule out some of the models, by querying them one by one, and the error goes away.

```
models = cat.df['source_id'].unique()
for model in models:
    print(f"+++++++{model}+++++++++")
    model_query = {k:v for k,v in query.items()}
    model_query['source_id'] = model
    model_cat = col.search(**model_query)
    print(model_cat.df)
    try:
        model_data_dict = model_cat.to_dataset_dict(zarr_kwargs={'consolidated': True, 'decode_times':False}, preprocess=combined_preprocessing)
    except Exception as e:
        print(f"{k} failed to preprocess")
        print(e)
```

Does this suggest that intake-esm is attempting an aggregation of several models, causing the error above? Either way I think more verbose output options could help me a lot pin this issue down. 

Thanks

**Comment by andersy005** [comment]
You can use the `log_level` argument for logging purposes.

```python
col = intake.open_esm_datastore(url, log_level='ERROR')
```

Accepted values are: `CRITICAL`, `ERROR`, `WARNING`, `INFO`, `DEBUG`, `NOTSET`

**Comment by jbusecke** [comment]
Very helpful. Thanks

**Comment by andersy005** [comment]
You are welcome! Is it okay to close this?

**Comment by jbusecke** [comment]
I think for now yes

**Comment by andersy005** [comment]
Feel free to reopen it in the future.
