### ISSUE TITLE
require_all_on usage

### ISSUE THREAD

**Issue by aaronspring** [NCAR/intake-esm#214]
### Description

How I understand `require_all_on` in search is awesome. Unfortunately, I dont get any results back when including this arg, although I should, see the gist below.

### What I Did
Minimal example:

https://gist.github.com/aaronspring/7d743cf6d96a34479ec8da6b3aee3181

**Comment by andersy005** [comment]
Thank you for reporting this, @aaronspring! 

It appears that the logic used is sensitive to strings vs iterables. As a temporary workaround, try changing the strings in your query to lists:

- Original

```python
query = dict(experiment_id=['historical','piControl'], source_id='CESM2',
             require_all_on='source_id',
             variable_id='tas', table_id='Amon'
            )
```

- Modified

```python
query = dict(experiment_id=['historical','piControl'], source_id=['CESM2'],
             require_all_on='source_id',
             variable_id=['tas'], table_id=['Amon']
            )
```

I am going to fix this by making sure that if the user provides a string, for e.g. `'Amon'`, intake-esm casts it to a list `['Amon']`. Also, I will cut a new release with this fix soon.

**Comment by andersy005** [comment]
@aaronspring, when you get a chance can you try the master branch, and let me know whether the bug is fixed? 

```bash
python -m pip install git+https://github.com/NCAR/intake-esm.git
```

**Comment by aaronspring** [comment]
your quick fix works. also after installing from source! great! thanks.

**Comment by andersy005** [comment]
A new version is available on PyPI and Conda-forge too.

Closing this for the time being. If you find any other bugs, feel free to reopen.
