### ISSUE TITLE
Automatically create catalog from synda filestructure on local filesystem

### ISSUE THREAD

**Issue by jbusecke** [NCAR/intake-esm#217]
I am currently downloading a subset of models/variables to the filesystem in Princeton using [synda](https://github.com/Prodiguer/synda).

If I am correct, this should produce a fairly standardized filestructure on our system.

My question is, is there an easy way to produce/update a catalog file, so that I could use intake-esm to load/aggreagate files. This would be amazing, because I could clone all my workflow from the pangeo cloud and transfer it to the local system.  

cc'ing our sysadmin @luet

**Comment by andersy005** [comment]
Take a look at https://github.com/NCAR/intake-esm-datastore/tree/master/builders directory. The `cmip.py` script is what we use at NCAR to build CMIP5/6 catalogs for the data downloaded using synda to Cheyenne's filesystem. 

Here's how I usually use it:


```bash
$ python cmip.py --root-path /glade/collections/cmip/CMIP6 --pick-latest-version --cmip-version 6 --csv-filepath ../catalogs/glade-cmip6.csv.gz --depth 4
```

And `/glade/collections/cmip/CMIP6` looks like this:

```bash
$ tree /glade/collections/cmip/CMIP6/ -d -L 2
/glade/collections/cmip/CMIP6/
├── AerChemMIP
│   ├── BCC
│   └── NCAR -> /glade/collections/cdg/data/CMIP6/AerChemMIP/NCAR
├── C4MIP
│   ├── BCC
│   ├── CCCma
│   ├── CNRM-CERFACS
│   ├── MOHC
│   ├── NASA-GISS
│   ├── NCAR -> /glade/collections/cdg/data/CMIP6/C4MIP/NCAR
│   └── NOAA-GFDL
├── CDRMIP
│   └── NCAR -> /glade/collections/cdg/data/CMIP6/CDRMIP/NCAR
├── CFMIP
│   └── NCAR -> /glade/collections/cdg/data/CMIP6/CFMIP/NCAR
├── CMIP
│   ├── AS-RCEC
│   ├── AWI
│   ├── BCC
│   ├── CAMS
│   ├── CAS
│   ├── CCCma
│   ├── CCCR-IITM
│   ├── CNRM-CERFACS
│   ├── CSIRO
│   ├── CSIRO-ARCCSS
│   ├── E3SM-Project
│   ├── EC-Earth-Consortium
│   ├── FIO-QLNM
│   ├── HAMMOZ-Consortium
│   ├── INM
│   ├── IPSL
│   ├── MIROC
│   ├── MOHC
│   ├── MPI-M
│   ├── MRI
│   ├── NASA-GISS
│   ├── NCAR -> /glade/collections/cdg/data/CMIP6/CMIP/NCAR
│   ├── NCC
│   ├── NIMS-KMA
│   ├── NOAA-GFDL
│   ├── NUIST
│   ├── SNU
│   └── UA
├── DAMIP
│   ├── BCC
│   ├── CCCma
│   ├── CNRM-CERFACS
│   ├── IPSL
│   ├── MIROC
│   ├── MOHC
│   ├── MRI
│   ├── NASA-GISS
│   ├── NCAR -> /glade/collections/cdg/data/CMIP6/DAMIP/NCAR
│   └── NCC
├── DCPP
│   ├── CCCma
│   ├── MIROC
│   └── NCAR -> /glade/collections/cdg/data/CMIP6/DCPP/NCAR
├── GeoMIP
│   └── NCAR -> /glade/collections/cdg/data/CMIP6/GeoMIP/NCAR
├── GMMIP
│   └── NCAR -> /glade/collections/cdg/data/CMIP6/GMMIP/NCAR
├── HighResMIP
│   ├── CAS
│   ├── CMCC
│   ├── CNRM-CERFACS
│   ├── ECMWF
│   ├── IPSL
│   ├── MIROC
│   ├── MOHC
│   ├── MPI-M
│   └── NOAA-GFDL
├── LS3MIP
│   └── NCAR -> /glade/collections/cdg/data/CMIP6/LS3MIP/NCAR
├── LUMIP
│   ├── BCC
│   ├── CCCma
│   ├── CNRM-CERFACS
│   ├── IPSL
│   ├── MOHC
│   ├── NCAR -> /glade/collections/cdg/data/CMIP6/LUMIP/NCAR
│   └── NOAA-GFDL
├── OMIP
│   ├── CAS
│   ├── CNRM-CERFACS
│   ├── IPSL
│   ├── MIROC
│   ├── NCAR -> /glade/collections/cdg/data/CMIP6/OMIP/NCAR
│   └── NOAA-GFDL
├── PAMIP
│   └── NCAR -> /glade/collections/cdg/data/CMIP6/PAMIP/NCAR
├── PMIP
│   ├── MIROC
│   └── NCAR -> /glade/collections/cdg/data/CMIP6/PMIP/NCAR
├── RFMIP
│   └── NCAR -> /glade/collections/cdg/data/CMIP6/RFMIP/NCAR
└── ScenarioMIP
    ├── AWI
    ├── BCC
    ├── CAMS
    ├── CAS
    ├── CCCma
    ├── CNRM-CERFACS
    ├── CSIRO
    ├── CSIRO-ARCCSS
    ├── DKRZ
    ├── DWD
    ├── EC-Earth-Consortium
    ├── FIO-QLNM
    ├── HAMMOZ-Consortium
    ├── INM
    ├── IPSL
    ├── MIROC
    ├── MOHC
    ├── MPI-M
    ├── MRI
    ├── NCAR -> /glade/collections/cdg/data/CMIP6/ScenarioMIP/NCAR
    ├── NCC
    ├── NIMS-KMA
    ├── NOAA-GFDL
    ├── NUIST
    ├── THU
    └── UA
```

**Comment by andersy005** [comment]
P.S.: Today, the catalog isn't built automatically. In order to update it, we still need to run the `cmip.py` script again.

**Comment by jbusecke** [comment]
Oh great! Thanks for the pointer. The data is still downloading, but I will most definitely try this out the next days and report back!

**Comment by jbusecke** [comment]
Oh man that worked beautifully! The one thing that would make this even easier, would be to provided a conda `envrionment.yml` with only the packages needed to construct the catalogue. Happy to submit mine if there is interest. 
Just out of curiosity: The structure of the `.json` file should be the same except for the path to the catalog csv, right? Thanks a lot for the tips, @andersy005!

**Comment by andersy005** [comment]
> Oh man that worked beautifully! The one thing that would make this even easier, would be to provided a conda envrionment.yml with only the packages needed to construct the catalogue.

Glad to hear that things worked smoothly :)  Thank you for the conda environment file suggestion. I just opened a PR to address this. 



> The structure of the .json file should be the same except for the path to the catalog csv, right? 

Yes. For CMIP6, you can copy the content of https://github.com/NCAR/intake-esm-datastore/blob/master/catalogs/glade-cmip6.json, and update the `catalog_file` entry with the location of your csv file. 

By the way, with the newest version of intake-esm, the `catalog_file` does not need to point to an absolute/full path. You can use a path relative to the JSON's i.e. `"catalog_file": "glade-cmip6.csv.gz",` instead of `"catalog_file": "/glade/collections/cmip/catalog/intake-esm-datastore/catalogs/glade-cmip6.csv.gz",`

**Comment by jbusecke** [comment]
Closing this. Thanks for the help
