### ISSUE TITLE
module 'intake' has no attribute 'open_esm_datastore'

### ISSUE THREAD

**Issue by sckw** [NCAR/intake-esm#224]
Hi, I am working on a jupyter notebook, and when trying:

import intake
col = intake.open_esm_datastore("https://storage.googleapis.com/cmip6/pangeo-cmip6.json")
col

I get the following error -

module 'intake' has no attribute 'open_esm_datastore'

What am I doing wrong here?

Best,
Suki

![image](https://user-images.githubusercontent.com/31698590/78415483-0da8f980-75f0-11ea-8d78-018b93116b72.png)

`conda list`
<details>
appdirs                   1.4.3                    pypi_0    pypi
asciitree                 0.3.3                      py_2    conda-forge
attrs                     19.3.0                     py_0    conda-forge
backcall                  0.1.0                      py_0    conda-forge
basemap                   1.2.1            py36h79c95a4_1    conda-forge
blas                      1.0                         mkl
bleach                    3.1.4              pyh9f0ad1d_0    conda-forge
blinker                   1.4                        py_1    conda-forge
bokeh                     1.4.0            py36h9f0ad1d_1    conda-forge
boto3                     1.12.32            pyh9f0ad1d_0    conda-forge
botocore                  1.15.32            pyh9f0ad1d_0    conda-forge
bottleneck                1.3.2            py36hbd37c6d_1    conda-forge
bzip2                     1.0.8                hfa6e2cd_2    conda-forge
ca-certificates           2019.11.28           hecc5488_0    conda-forge
cachetools                3.1.1                      py_0    conda-forge
cartopy                   0.17.0          py36hfff79a3_1006    conda-forge
certifi                   2019.11.28       py36h9f0ad1d_1    conda-forge
cffi                      1.14.0           py36ha419a9e_0    conda-forge
cftime                    1.1.1.2          py36hbd37c6d_0    conda-forge
chardet                   3.0.4           py36h9f0ad1d_1006    conda-forge
click                     7.1.1              pyh8c360ce_0    conda-forge
cloudpickle               1.3.0                      py_0    conda-forge
colorama                  0.4.3                      py_0    conda-forge
configobj                 5.0.6                      py_0    conda-forge
cryptography              2.8              py36hb32ad35_1    conda-forge
curl                      7.68.0               h4496350_0    conda-forge
cycler                    0.10.0                     py_2    conda-forge
cython                    0.29.16          py36hbd05846_0    conda-forge
cytoolz                   0.10.1           py36hfa6e2cd_0    conda-forge
dask                      2.13.0                     py_0    conda-forge
dask-core                 2.13.0                     py_0    conda-forge
decorator                 4.4.2                      py_0    conda-forge
defusedxml                0.6.0                      py_0    conda-forge
distributed               2.13.0           py36h9f0ad1d_0    conda-forge
docutils                  0.15.2                   py36_0    conda-forge
entrypoints               0.3             py36h9f0ad1d_1001    conda-forge
fasteners                 0.14.1                     py_3    conda-forge
freetype                  2.10.1               ha9979f8_0    conda-forge
fsspec                    0.7.1                      py_0    conda-forge
gcsfs                     0.6.1                      py_0    conda-forge
geos                      3.7.2                he025d50_2    conda-forge
google-auth               1.12.0             pyh9f0ad1d_0    conda-forge
google-auth-oauthlib      0.4.1                      py_2    conda-forge
h5py                      2.10.0          nompi_py36h422b98e_102    conda-forge
hdf4                      4.2.13            hf8e6fe8_1003    conda-forge
hdf5                      1.10.5          nompi_ha405e13_1104    conda-forge
heapdict                  1.0.1                      py_0    conda-forge
icc_rt                    2019.0.0             h0cc432a_1
icu                       64.2                 he025d50_1    conda-forge
idna                      2.9                        py_1    conda-forge
imageio                   2.8.0                      py_0    conda-forge
importlib-metadata        1.6.0            py36h9f0ad1d_0    conda-forge
importlib_metadata        1.6.0                         0    conda-forge
intake                    0.5.5                    pypi_0    pypi
intake-esm                2020.3.16.2              pypi_0    pypi
intel-openmp              2019.4                      245
ipykernel                 5.2.0            py36h5ca1d4c_1    conda-forge
ipython                   7.13.0           py36h9f0ad1d_2    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.5.1                      py_0    conda-forge
jedi                      0.16.0           py36h9f0ad1d_1    conda-forge
jinja2                    2.11.1                     py_0    conda-forge
jmespath                  0.9.5                      py_0    conda-forge
joblib                    0.14.1                     py_0    conda-forge
jpeg                      9c                hfa6e2cd_1001    conda-forge
json5                     0.9.0                      py_0    conda-forge
jsonschema                3.2.0            py36h9f0ad1d_1    conda-forge
jupyter                   1.0.0                      py_2    conda-forge
jupyter_client            6.1.2                      py_0    conda-forge
jupyter_console           6.1.0                      py_1    conda-forge
jupyter_core              4.6.3            py36h9f0ad1d_1    conda-forge
jupyterlab                2.0.1                      py_0    conda-forge
jupyterlab_server         1.1.0                      py_0    conda-forge
kiwisolver                1.1.0            py36h246c5b5_1    conda-forge
krb5                      1.16.4               hdd46e55_0    conda-forge
libblas                   3.8.0                    14_mkl    conda-forge
libcblas                  3.8.0                    14_mkl    conda-forge
libclang                  9.0.1           default_hf44288c_0    conda-forge
libcurl                   7.68.0               h4496350_0    conda-forge
liblapack                 3.8.0                    14_mkl    conda-forge
libnetcdf                 4.7.4           nompi_hc957ea6_101    conda-forge
libpng                    1.6.37               hfe6a214_1    conda-forge
libsodium                 1.0.17               h2fa13f4_0    conda-forge
libssh2                   1.8.2                h642c060_2    conda-forge
libtiff                   4.1.0                h885aae3_6    conda-forge
locket                    0.2.0                      py_2    conda-forge
lz4-c                     1.8.3             he025d50_1001    conda-forge
m2w64-gcc-libgfortran     5.3.0                         6
m2w64-gcc-libs            5.3.0                         7
m2w64-gcc-libs-core       5.3.0                         7
m2w64-gmp                 6.1.0                         2
m2w64-libwinpthread-git   5.0.0.4634.697f757               2
markupsafe                1.1.1            py36h68a101e_1    conda-forge
matplotlib                3.2.1                         0    conda-forge
matplotlib-base           3.2.1            py36hf0cddfc_0    conda-forge
mistune                   0.8.4           py36hfa6e2cd_1000    conda-forge
mkl                       2019.4                      245
mkl-service               2.3.0            py36hfa6e2cd_0    conda-forge
monotonic                 1.5                        py_0    conda-forge
msgpack-python            1.0.0            py36h246c5b5_1    conda-forge
msys2-conda-epoch         20160418                      1
nbconvert                 5.6.1                    py36_0    conda-forge
nbformat                  5.0.4                      py_0    conda-forge
netcdf4                   1.5.3           nompi_py36h86f0940_103    conda-forge
networkx                  2.4                        py_1    conda-forge
notebook                  6.0.3                    py36_0    conda-forge
numcodecs                 0.6.4            py36h6538335_0    conda-forge
numpy                     1.18.1           py36h48dd78f_1    conda-forge
oauthlib                  3.0.1                      py_0    conda-forge
olefile                   0.46                       py_0    conda-forge
openssl                   1.1.1f               hfa6e2cd_0    conda-forge
owslib                    0.19.2                     py_0    conda-forge
packaging                 20.1                       py_0    conda-forge
pandas                    1.0.3            py36h5076640_0    conda-forge
pandoc                    2.9.2                         0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
parso                     0.6.2                      py_0    conda-forge
partd                     1.1.0                      py_0    conda-forge
patsy                     0.5.1                      py_0    conda-forge
pickleshare               0.7.5           py36h9f0ad1d_1001    conda-forge
pillow                    7.0.0            py36h8ffffea_1    conda-forge
pip                       20.0.2                     py_2    conda-forge
proj4                     5.2.0             h6538335_1006    conda-forge
prometheus_client         0.7.1                      py_0    conda-forge
prompt-toolkit            3.0.5                      py_0    conda-forge
prompt_toolkit            3.0.5                         0    conda-forge
psutil                    5.7.0            py36h68a101e_1    conda-forge
pyasn1                    0.4.8                      py_0    conda-forge
pyasn1-modules            0.2.7                      py_0    conda-forge
pycparser                 2.20                       py_0    conda-forge
pyepsg                    0.4.0                      py_0    conda-forge
pygments                  2.6.1                      py_0    conda-forge
pyjwt                     1.7.1                      py_0    conda-forge
pykdtree                  1.3.1           py36hbd37c6d_1003    conda-forge
pyopenssl                 19.1.0                     py_1    conda-forge
pyparsing                 2.4.6                      py_0    conda-forge
pyproj                    1.9.6           py36hfa6e2cd_1002    conda-forge
pyqt                      5.12.3           py36h6538335_1    conda-forge
pyqt5-sip                 4.19.18                  pypi_0    pypi
pyqtwebengine             5.12.1                   pypi_0    pypi
pyreadline                2.1                   py36_1001    conda-forge
pyresample                1.15.0           py36h5076640_0    conda-forge
pyrsistent                0.16.0           py36h68a101e_0    conda-forge
pyshp                     2.1.0                      py_0    conda-forge
pysocks                   1.7.1            py36h9f0ad1d_1    conda-forge
python                    3.6.10          he025d50_1009_cpython    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python_abi                3.6                     1_cp36m    conda-forge
pytz                      2019.3                     py_0    conda-forge
pywavelets                1.1.1            py36hc8d92b1_0    conda-forge
pywin32                   227              py36hfa6e2cd_0    conda-forge
pywinpty                  0.5.7                    py36_0    conda-forge
pyyaml                    5.3.1            py36h68a101e_0    conda-forge
pyzmq                     19.0.0           py36ha89082f_1    conda-forge
qt                        5.12.5               h7ef1ec2_0    conda-forge
qtconsole                 4.7.2              pyh9f0ad1d_0    conda-forge
qtpy                      1.9.0                      py_0    conda-forge
requests                  2.23.0             pyh8c360ce_2    conda-forge
requests-oauthlib         1.2.0                      py_0    conda-forge
rsa                       4.0                        py_0    conda-forge
s3fs                      0.4.2                      py_0    conda-forge
s3transfer                0.3.3            py36h9f0ad1d_0    conda-forge
scikit-image              0.16.2           py36he350917_0    conda-forge
scikit-learn              0.22.2.post1     py36h7208079_0    conda-forge
scipy                     1.3.1            py36h29ff71c_0    conda-forge
seaborn                   0.10.0                     py_1    conda-forge
send2trash                1.5.0                      py_0    conda-forge
setuptools                46.1.3           py36h9f0ad1d_0    conda-forge
shapely                   1.6.4           py36ha35856d_1006    conda-forge
six                       1.14.0                     py_1    conda-forge
sortedcontainers          2.1.0                      py_0    conda-forge
sqlite                    3.30.1               hfa6e2cd_0    conda-forge
statsmodels               0.11.1           py36h68a101e_1    conda-forge
tblib                     1.6.0                      py_0    conda-forge
terminado                 0.8.3            py36h9f0ad1d_1    conda-forge
testpath                  0.4.4                      py_0    conda-forge
tk                        8.6.10               hfa6e2cd_0    conda-forge
toolz                     0.10.0                     py_0    conda-forge
tornado                   6.0.4            py36hfa6e2cd_0    conda-forge
tqdm                      4.44.1             pyh9f0ad1d_0    conda-forge
traitlets                 4.3.3            py36h9f0ad1d_1    conda-forge
urllib3                   1.25.7           py36h9f0ad1d_1    conda-forge
vc                        14.1                 h869be7e_1    conda-forge
vs2015_runtime            14.16.27012          h30e32a0_1    conda-forge
wcwidth                   0.1.9              pyh9f0ad1d_0    conda-forge
webencodings              0.5.1                      py_1    conda-forge
wheel                     0.34.2                     py_1    conda-forge
widgetsnbextension        3.5.1                    py36_0    conda-forge
win_inet_pton             1.1.0                    py36_0    conda-forge
wincertstore              0.2                   py36_1003    conda-forge
winpty                    0.4.3                         4    conda-forge
xarray                    0.15.1                     py_0    conda-forge
xz                        5.2.4             h2fa13f4_1002    conda-forge
yaml                      0.2.2                hfa6e2cd_1    conda-forge
zarr                      2.4.0                      py_0    conda-forge
zeromq                    4.3.2                h6538335_2    conda-forge
zict                      2.0.0                      py_0    conda-forge
zipp                      3.1.0                      py_0    conda-forge
zlib                      1.2.11            h2fa13f4_1006    conda-forge
zstd                      1.4.4                hd8a0e53_2    conda-forge
</details>

### Description

```
Trying to read in CMIP6 data, using intake.open_esm_datastore and got an attribute error (see image)
```

### What I Did

```
cat_url = "https://storage.googleapis.com/cmip6/pangeo-cmip6.json"
col = intake.open_esm_datastore(cat_url)
col
```

### Output of ``intake_esm.__version__``

<details>

'2020.3.16.2'

</details>

**Comment by andersy005** [comment]
Hello @sckw, 

Can you confirm that `intake-esm` is installed in your Python environment by running 

```bash
conda list intake
```

Or 

```bash
pip show intake-esm
```
?

**Comment by sckw** [comment]
![image](https://user-images.githubusercontent.com/31698590/78464686-54632600-76ba-11ea-995a-5b1c7e0166db.png)

Yes, I can confirm that intake-esm is installed

**Comment by andersy005** [comment]
In your notebook, what is the output of

```python
import sys
sys.executable
```

**Comment by sckw** [comment]
that outputs the following

`C:\Users\sukic\Anaconda3\envs\geosci\python.exe`

**Comment by andersy005** [comment]
Thanks for the update. Do you get any output when try the following??

```python
print(intake.registry)
```

**Comment by sckw** [comment]
Thank you for helping to diagnose. Yes, I get:

`DriverRegistryView({'yaml_file_cat': <class 'intake.catalog.local.YAMLFileCatalog'>, 'yaml_files_cat': <class 'intake.catalog.local.YAMLFilesCatalog'>, 'catalog': <class 'intake.catalog.base.Catalog'>, 'csv': <class 'intake.source.csv.CSVSource'>, 'intake_remote': <class 'intake.catalog.base.RemoteCatalog'>, 'ndzarr': <class 'intake.source.zarr.ZarrArraySource'>, 'numpy': <class 'intake.source.npy.NPySource'>, 'textfiles': <class 'intake.source.textfiles.TextFilesSource'>, 'esm_datastore': <class 'intake_esm.core.esm_datastore'>})`

**Comment by andersy005** [comment]
It appears that `'esm_datastore': <class 'intake_esm.core.esm_datastore'>` is present in the intake registry. So, I am not sure why you are getting `module 'intake' has no attribute 'open_esm_datastore'`. I may need to diagnose the issue on a windows machine (some time next week) to see what's going on.

**Comment by sckw** [comment]
Okay, that would be great if you could figure something out. I am new to intake, so it was unfortunate that I ran straight into an issue... I can also see if I know anyone who uses intake on a windows machine to diagnose.

Thanks again, have a good rest of the weekend.

**Comment by anuragap98** [comment]
Anyone find the solution to this issue - 
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-3-8722c240ef21> in <module>
      1 # Open collection description file
      2 catalog_url = 'https://ncar-cesm-lens.s3-us-west-2.amazonaws.com/catalogs/aws-cesm1-le.json'
----> 3 col = intake.open_esm_datastore(catalog_url)
      4 col

AttributeError: module 'intake' has no attribute 'open_esm_datastore'

**Comment by swartn** [comment]
I'm still experience this issue under linux, and can confirm intake-esm is installed as above.

**Comment by andersy005** [comment]
@anuragap98, @swartn  

> I'm still experience this issue under linux, and can confirm intake-esm is installed as above.

Can you confirm that you are running the right kernel by running the following:

```python
import intake_esm
print(intake_esm.__version__)

import sys
print(sys.executable)
```

**Comment by singh-shikha** [comment]
Hi, 

I am a very new user of Pangeo. I started today itself and have ran in this issue. Here is the screenshot of error and kernel details:
![image](https://user-images.githubusercontent.com/18552910/130453681-d709261b-668d-4cc9-9df7-4285e4e828dd.png)

![image](https://user-images.githubusercontent.com/18552910/130453493-622032dd-e03a-4b3e-9fed-e8bf1a75f346.png)
![image](https://user-images.githubusercontent.com/18552910/130453576-c31d7d51-6b50-487c-8ee8-443b07b3e8a3.png)
  Please help.

**Comment by tanthiamhuat** [comment]
restart Python kernel.

**Comment by KashyapAnurag** [comment]
In most of the cases in such scenario " module 'intake' has no attribute 'open_esm_datastore" , Restarting the kernel works, If the installations are correct. 

Maybe you can check the version of intake-esm and update it!

Ps: For my case, it has worked, hope this is a common problem.
