### ISSUE TITLE
Progressbar gets chopped up by preprocessing print statements.

### ISSUE THREAD

**Issue by jbusecke** [NCAR/intake-esm#231]
I just played a little bit with the newest version and noticed that print statements from preprocessing end up chopping the status bar into this super long thing: 
![image](https://user-images.githubusercontent.com/14314623/81019407-9b1c7b00-8e34-11ea-8429-8e9489460c7b.png)

Is there a way to prevent that? Happy to implement in cmip6_pp upstream if that would help.

**Comment by andersy005** [comment]
This is a tqdm issue: https://github.com/tqdm/tqdm/issues/375. There is a workaround for this: https://github.com/tqdm/tqdm/issues/375#issuecomment-328466265. https://github.com/NCAR/intake-esm/blob/31ba8b5818c2f8255c24be52463302bd9b2062e4/intake_esm/core.py#L10

Would you be interested in submitting a PR for this? 

Another temporary solution is to disable the progressbar (assuming you don't need it :)).

**Comment by jbusecke** [comment]
Is it literally just that one line I have to replace? Then, of course.

**Comment by andersy005** [comment]
> Is it literally just that one line I have to replace? 

I think so. Try testing the one line change with your existing notebook to see if the problem goes away. Looking forward to the PR :)

**Comment by andersy005** [comment]
Should be fixed by #238

**Comment by jbusecke** [comment]
Just updated to the newest master on my working env, and I just wanted to say: I really like the look of the new progressbars!

**Comment by andersy005** [comment]
Glad to hear that the new progress-bar is much better! Closing....
