### ISSUE TITLE
move `overwrite_existing` to function api

### ISSUE THREAD

**Issue by matt-long** [NCAR/intake-esm#40]
`overwrite_existing` is now defined in the input file for `open_esm_metadatastore`.

This should be a separate function argument.

**Comment by andersy005** [comment]
Do you mean something like passing this argument to this function https://github.com/NCAR/intake-esm/blob/master/intake_esm/core.py#L96 and/or some other function involved in collection build?

**Comment by matt-long** [comment]
Yes. The collection input file specifies the information necessary to generate a collection, but  `overwrite_existing` is more of a programatic control option, not really an attribute of the collection.

**Comment by andersy005** [comment]
@matt-long, now that you suggest moving `overwrite_existing` to function API, should we do the same thing for `include_cache_dir`?

**Comment by matt-long** [comment]
Yes, I think so. I could see this `include_cache_dir` going away in the case where we have an automated `gather_data` method.
