### ISSUE TITLE
keeping CMIP6 tracking_id values

### ISSUE THREAD

**Issue by naomi-henderson** [NCAR/intake-esm#53]
@andersy005 and @matt-long , I am loving the `intake-esm` Collection Catalog and use the CMIP6 version extensively on our local collection!  Building a collection is painless, the search method is useful and `to_xarray` works like a charm. But it looks like we need a small addition for CMIP6.

This only pertains to CMIP6 because the CMIP5 "system-centric" methodology has morphed into a CMIP6 "dataset-centric" one for dealing with issues such as errata/retractions, licensing and persistent identifiers.  See [Balaji et al., 2018, 'Requirements for a global data infrastucture in support of CMIP6'](https://doi.org/10.5194/gmd-11-3659-2018)).  They now put a 'Handle' in each netcdf4 file - an attribute called `tracking_id` - to be used with a 'Global Handle Registry'.

The upshot is that we should include `tracking_id` in the list of `merge_keys` in `aggregate.py`.  Unlike `history`, this is only for CMIP6, so can't just be added as a default for all. We definitely need to concatenate the `tracking_id` because they are unique identifiers for each original netcdf4 file. Possible?

**Comment by andersy005** [comment]
@naomi-henderson, this is definitely feasible! I will look into it and will let you know once I have a PR ready

**Comment by andersy005** [comment]
@naomi-henderson, 

When inspecting `dict_union` function in `aggregate.py`, I found out that the most straightforward fix for this issue is changing the default value of  `merge_keys` to `merge_keys=['history', 'tracking_id']`



> Unlike history, this is only for CMIP6, so can't just be added as a default for all. 

Because of these four lines:

```python
if (v1 is None and v2 is None) or k in drop_keys:
                pass
```
```python
elif k in merge_keys:
     d[k] = '\n'.join([v1, v2])
```

having `merge_keys=['history', 'tracking_id']` won't have any effects to other datasets that don't have this attribute:


```python
def dict_union(*dicts, merge_keys=['history', 'tracking_id'], drop_keys=[]):
    """Return the union of two or more dictionaries."""
    if len(dicts) > 2:
        return reduce(dict_union, dicts)
    elif len(dicts) == 2:
        d1, d2 = dicts
        d = type(d1)()
        # union
        all_keys = set(d1) | set(d2)
        for k in all_keys:
            v1 = d1.get(k)
            v2 = d2.get(k)
            if (v1 is None and v2 is None) or k in drop_keys:
                pass
            elif v1 is None:
                d[k] = v2
            elif v2 is None:
                d[k] = v1
            elif v1 == v2:
                d[k] = v1
            elif k in merge_keys:
                d[k] = '\n'.join([v1, v2])
        return d
    elif len(dicts) == 1:
        return dicts[0]
```

## CMIP6 Data 

```python
x1 = OrderedDict([('history',
              '2018-10-16T01:20:04Z ; CMOR rewrote data to be consistent with CMIP6, CF-1.7 CMIP-6.2 and CF standards.'),
             ('tracking_id',
              'hdl:21.14100/a0b2775e-e1b2-4dc2-9d49-4d5809a57907'),
             ('description', 'DECK: abrupt4xCO2')])
x2 = OrderedDict([('history',
              'Thu Jul 26 18:44:21 2018: ncatted -O -a tracking_id,global,m,c,hdl:21.14100/5e59a40f-30f0-4098-b6eb-2bf5653cabd6 evspsblveg_Lmon_IPSL-CM6A-LR_1pctCO2_r1i1p1f1_gr_185001-199912.nc\nnone'),
             ('tracking_id',
              'hdl:21.14100/5e59a40f-30f0-4098-b6eb-2bf5653cabd6'),
             ('description', 'DECK: 1pctCO2')])

x = dict_union(x1, x2)
x

OrderedDict([('tracking_id',
              'hdl:21.14100/a0b2775e-e1b2-4dc2-9d49-4d5809a57907\nhdl:21.14100/5e59a40f-30f0-4098-b6eb-2bf5653cabd6'),
             ('history',
              '2018-10-16T01:20:04Z ; CMOR rewrote data to be consistent with CMIP6, CF-1.7 CMIP-6.2 and CF standards.\nThu Jul 26 18:44:21 2018: ncatted -O -a tracking_id,global,m,c,hdl:21.14100/5e59a40f-30f0-4098-b6eb-2bf5653cabd6 evspsblveg_Lmon_IPSL-CM6A-LR_1pctCO2_r1i1p1f1_gr_185001-199912.nc\nnone')])
```


## CMIP5 Data

```python
y1 = OrderedDict([('history',
              '2011-11-15T23:09:22Z CMOR rewrote data to comply with CF standards and CMIP5 requirements.'),
             ('creation_date', '2011-11-15T23:09:22Z'),
             ('title',
              'BNU-ESM model output prepared for CMIP5 ESM pre-industrial control')])
​
y2 = OrderedDict([('history',
              '2009-06-29T16:41:05Z CMOR rewrote data to comply with CF standards and CMIP5 requirements.'),
             ('creation_date', '2009-06-29T16:41:05Z'),
             ('title',
              'FIO-ESM model output prepared for CMIP5 ESM historical')])

y = dict_union(y1, y2)
y

OrderedDict([('history',
              '2011-11-15T23:09:22Z CMOR rewrote data to comply with CF standards and CMIP5 requirements.\n2009-06-29T16:41:05Z CMOR rewrote data to comply with CF standards and CMIP5 requirements.')])
```

**Comment by naomi-henderson** [comment]
@andersy005 , Many thanks!  Your test cases show that it is doing just what is needed.
