### ISSUE TITLE
Needed Code Refactoring 

### ISSUE THREAD

**Issue by andersy005** [NCAR/intake-esm#70]
It appears that for the last few months, we've accumulated some technical debt:

- Lack of necessary user-facing supporting documentation on how to extend intake-esm
- Delayed refactoring: more code was added without refactoring 
- A few components have become tightly-coupled which resulted in  situations where some  functions are not modular, making the package not flexible enough to extend without code duplication

As more people are finding intake-esm useful for their own use cases, it would be nice to do some code refactoring soon in order to make intake-esm flexible enough to extend and use.

**Comment by matt-long** [comment]
Clean up test directory to clearly distinguish input from out, file types, etc.

**Comment by andersy005** [comment]
Addressed in #77
