### ISSUE TITLE
inconsistent application of reset_coords

### ISSUE THREAD

**Issue by matt-long** [NCAR/intake-esm#71]
We are not consistent in the structure of the datasets we return. 

If there is an `ensemble` dimension, we apply the `reset_coords` method to change variables that we set as coordinates for convenience and that do not have corresponding dimensions back to `data_vars`
https://github.com/NCAR/intake-esm/blob/57d99a0184f296acec977ab004471cc4faa7bff7/intake_esm/aggregate.py#L171-L172

However, if there is no ensemble dimension, this reset is not applied. Having things like `time_bound` as a coordinate confuses other tools (i.e., `esmlab`), so I think we should always apply this reset.

**Comment by andersy005** [comment]
Fixed in #91
