### ISSUE TITLE
quiet option

### ISSUE THREAD

**Issue by matt-long** [NCAR/intake-esm#75]
I am looping over several queries into a catalog to process datasets. Each call to `.to_xarray()` generates tqdm output...which accumulates with each iteration of my loop. It would be nice to (a) turn this off or (b) replace the status information in situ, rather than append new status bars.

**Comment by andersy005** [comment]
@matt-long, this has been addressed in #119 

```python
from intake_esm import config
config.set({'progress-bar': False})
```
