### ISSUE TITLE
latest option for CMIP6 versions

### ISSUE THREAD

**Issue by fanchic** [NCAR/intake-esm#76]
Hey Guys,

Is there a way to grab the latest version of the files with intake-esm, it seems that when I pipe the result of my search to xarray it uses all versions of the files. It would be really useful to get the latest version.

I know that for CMIP5 we used to have a symlink DRS tree with a latest directory that used to solve that issue. I was wondering what you guys have planned to insure that you don't concatenate times of different versions of the same file.

Thanks,

Francois

**Comment by n-henderson** [comment]
@fanchic - Yes, all versions of the files are kept.  There are two ways I use to deal with this, probably others have their own methods.  Both of mine involve an intermediate step.  For our local repository,  I just keep a separate symlink tree of links to the latest versions of all.  For our GC repository we create a (deep nested) intake catalog which includes only the latest versions.  

Do you have any other ideas? An option to the intake-esm search perhaps?

**Comment by naomi-henderson** [comment]
hmmm, my version of intake_esm ('2019.4.26.1') already selects only the latest version of the cmip6 file - has this changed?

from  `common.py`:
```
        sorted_df = (
            df.sort_values('version')
            .drop_duplicates(subset='file_basename', keep='last')
            .reset_index(drop=True)
```

**Comment by andersy005** [comment]
> I was wondering what you guys have planned to insure that you don't concatenate times of different versions of the same file.

@fanchic, as @naomi-henderson pointed out, we only keep the latest version for each file. Therefore, when loading data into xarray, it is guaranteed that you won't have any conflicting versions of the same file. 

>  has this changed?

@naomi-henderson, as far as I can remember, we've always kept the latest version of files as the default behavior when building CMIP catalogs.

**Comment by fanchic** [comment]
ok guys, i found the issue, it is because the duplicates are searched for same "file_basename". So in this example there is a problem.

['pr_Amon_GFDL-CM4_historical_r1i1p1f1_gr1_185001-185412.nc',
 'tas_Amon_GFDL-CM4_historical_r1i1p1f1_gr1_185001-185412.nc',
 'pr_Amon_GFDL-CM4_historical_r1i1p1f1_gr1_185001-194912.nc',
 'pr_Amon_GFDL-CM4_historical_r1i1p1f1_gr1_195001-201412.nc',
 'tas_Amon_GFDL-CM4_historical_r1i1p1f1_gr1_185001-194912.nc',
 'tas_Amon_GFDL-CM4_historical_r1i1p1f1_gr1_195001-201412.nc']

The first version of the file who only has four years is loaded in the catalog because the files have different names. I am not sure what is the right approach here but I suggest to look at the match for 

/g/data/oi10/replicas/CMIP6/CMIP/NOAA-GFDL/GFDL-CM4/historical/r1i1p1f1/Amon/pr/gr1/

So before the version tag.

What do you think ?

**Comment by n-henderson** [comment]
@fanchic  - The four year files are (currently) not in the ESGF repositories at LLNL so I do not have this issue. Maybe someone forgot to remove them from the filesystem you are looking at?  It is very unusual for there to be duplicated time intervals and you should probably get someone to correct this.

**Comment by aaronspring** [comment]
I have the same issue and it wasnt there when I used the april version of intake-esm.

Based on what was implemented in `common.py`, I tried a workaround but this only changes the query_results but not the query:
```python
# doesnt work
def rm_version_dublicates(col):
    df = col.query_results
    sorted_df = (df.sort_values('version').drop_duplicates(subset='file_basename', keep='last').reset_index(drop=True))
    col.query_results = sorted_df
    return col
```

**Comment by andersy005** [comment]
@fanchic, @aaronspring 

If you know which files are problematic, you can add them to `exclude_dirs` section in the YAML file

```yaml
name: GLADE-CMIP6
collection_type: cmip6
data_sources:
  GLADE-DATA:
    locations:
      - name: CMIP-AP
        loc_type: posix
        direct_access: True 
        urlpath: /glade/collections/cmip/CMIP6
        exclude_dirs: ['*/pr_Amon_GFDL-CM4_historical_r1i1p1f1_gr1_185001-185412.nc']
        file_extension: .nc
```

and they will be excluded when the catalog is built..

**Comment by aaronspring** [comment]
the number of files is increasing from weeks to weeks. its all the newly uploaded data I guess and older data isnt taken down. for me it works with this fix

**Comment by andersy005** [comment]
@aaronspring, thank you for the feedback. 

@fanchic, I am going to close this issue for now. Feel free to reopen it.
